library(pointblank)

agent <-
  create_agent(
    tbl      = ~ the$clog$care$current,
    actions  = action_levels(warn_at = 0.05, stop_at = 0.10),
    tbl_name = "current_care",
    label    = "Validation plan generated by `draft_validation()`."
  ) |>
  row_count_match(count = 146) |>
  col_count_match(count = 12) |>
  rows_distinct(
    columns = c(
      "title",
      "description",
      "identifier",
      "references",
      "modified",
      "periodicity",
      "contact",
      "temporal",
      "dictionary",
      "site",
      "download",
      "resources"
    )
  ) |>
  col_schema_match(
    schema = col_schema(
      title       = "character",
      description = "character",
      identifier  = "character",
      references  = "character",
      modified    = "Date",
      periodicity = "character",
      contact     = "character",
      temporal    = "character",
      dictionary  = "character",
      site        = "character",
      download    = "character",
      resources   = "character"
    )
  ) |>
  interrogate()

report <-
  get_agent_report(
    agent = agent,
    display_table = FALSE
  )

report
