# MEDICAID
quick("MLR")
quick("enterprise")
quick("demographics")

# PROVIDER
quick("suppliers")
quick("PDC")
quick("MIPS")
quick("LTCH")
quick("IRF")
quick("SPICE")
quick("CAHPS_SPICE")
quick("CAHPS_HHC")
quick("CAHPS_ICH")
quick("CAHPS_OAS")
quick("HCAHPS")
quick("HHVBP")
quick("SNF_VBP")
quick("SNF_quality")
quick("NURSING_HOMES")

# OPEN PAYMENTS
quick("summary")
quick("profile")

# MEDICARE
quick("HHA")
quick("hospice")
quick("hospital")
quick("RHC")
quick("FQHC")
quick("pending")
quick("reassignment")
quick("SNF")

quick("contact")
quick("crosswalk")
quick("CARE_dialysis")
quick("enrollees")
quick("facilities")
quick("IQIES")
quick("laboratories")
quick("long_term")
quick("opt_out")
quick("order_refer")
quick("RBCS")
quick("transparency")

# quick("PDC")
# quick("MIPS")
# quick("LTCH")
# quick("IRF")
# quick("SPICE")
# quick("CAHPS_hospice")
# quick("HHVBP")
# quick("HHCA")
# quick("HHCAHPS")
# quick("SNF_VBP")
# quick("SNF_quality")
# quick("NH_pro")

# quick("suppliers")
#
# quick("HHA")
# quick("hospice")
# quick("hospital")
# quick("RHC")
# quick("FQHC")
# quick("pending")
# quick("reassignment")
# quick("SNF")
#
# quick("quality_payment")
#
# quick("contact")
# quick("crosswalk")
# quick("CARE_dialysis")
# quick("enrollees")
# quick("facilities")
# quick("IQIES")
# quick("laboratories")
# quick("long_term")
# quick("opt_out")
# quick("order_refer")
# quick("RBCS")
# quick("transparency")
# quick("summary")
# quick("profile")
# quick("MLR")
# quick("enterprise")

# quick("demographics")
