# ------- care_list ------
#' @autoglobal
#' @noRd
care_list <- list(
  endpoint = list(
    ahqr_psi11              = "^Agency for Healthcare Research and Quality \\(AHRQ\\) Patient Safety Indicator 11 \\(PSI[-]11\\) Measure Rates$",
    aip_plan                = "^Advance Investment Payment Spend Plan$",
    cpc_primary             = "^CPC Initiative [-] Participating Primary Care Practices$",
    cpc_joint               = "^Comprehensive Care for Joint Replacement Model[:] Metropolitan Statistical Areas$",
    county_risk_spend       = "^County[-]level Aggregate Expenditure and Risk Score Data on Assignable Beneficiaries$",
    hac_measures            = "^Deficit Reduction Act Hospital[-]Acquired Condition Measures$",
    esrd_group_perf         = "^End-Stage Renal Disease Facility Aggregation Group Performance$",
    fiss_rendering          = "^Fiscal Intermediary Shared System Attending and Rendering$",
    home_infusion           = "^Home Infusion Therapy Providers$",
    ffs_cert                = "^Medicare Fee[-]for[-]Service Comprehensive Error Rate Testing$",
    diabetes_prevention     = "^Medicare Diabetes Prevention Program$",
    clinician_group         = "^Managing Clinician Aggregation Group Performance$",
    lab_fee_schedule        = "^Medicare Clinical Laboratory Fee Schedule Private Payer Rates and Volumes$",
    aco_reach_aligned       = "^ACO REACH Aligned Beneficiaries$",
    aco_reach_eligible      = "^ACO REACH Eligible Beneficiaries$",
    aco_reach_results       = "^ACO REACH Financial and Quality Results$",
    aco_reach_providers     = "^ACO REACH Providers$",
    aco_reach_orgs          = "^REACH ACOs$",
    aco_pioneer             = "^Pioneer ACO Model$",
    aco_participants        = "^Accountable Care Organization Participants$",
    aco_snf_affiliate       = "^Accountable Care Organization Skilled Nursing Facility Affiliates$",
    aco_organizations       = "^Accountable Care Organizations$",
    aco_bene_cnty           = "^Number of Accountable Care Organization Assigned Beneficiaries by County$",
    care_dialysis           = "^Medicare Dialysis Facilities$",
    care_enrollees          = "Public Provider Enrollment",
    care_facilities         = "^Provider of Services File [-] Hospital & Non[-]Hospital Facilities$",
    care_pos_iqies          = "^Provider of Services File [-] Internet Quality Improvement and Evaluation System [-] Home Health Agency, Ambulatory Surgical Center, and Hospice Providers$",
    care_pos_labs           = "^Provider of Services File [-] Clinical Laboratories$",
    care_ltcf               = "^Long[-]Term Care Facility Characteristics$",
    care_opt_out            = "^Opt Out Affidavits$",
    care_order_refer        = "^Order and Referring$",
    care_restruct_betos     = "^Restructured BETOS Classification System$",
    care_miss_contact       = "^Public Reporting of Missing Digital Contact Information$",
    care_taxonomy_crosswalk = "^Medicare Provider and Supplier Taxonomy Crosswalk$",
    care_caid_managed_care  = "^Medicaid Managed Care",
    care_caid_opioid_geo    = "^Medicaid Opioid Prescribing Rates [-] by Geography",
    care_caid_drug_spend    = "^Medicaid Spending by Drug",
    care_benes              = "^Medicare Monthly Enrollment$",
    cms_ma_enroll           = "^CMS Program Statistics [-] Medicare Advantage [&] Other Health Plan Enrollment$",
    cms_ma_outpatient       = "^CMS Program Statistics [-] Medicare Advantage [-] Outpatient Facility$",
    cms_ma_other            = "^CMS Program Statistics [-] Medicare Advantage [-] Physician, Non[-]Physician Practitioner [&] Supplier$",
    cms_ma_inpatient        = "^CMS Program Statistics [-] Medicare Advantage[-]Inpatient Hospital$",
    cms_ma_snf              = "^CMS Program Statistics [-] Medicare Advantage[-]Skilled Nursing Facility$",
    cms_deaths              = "^CMS Program Statistics [-] Medicare Deaths$",
    cms_hha                 = "^CMS Program Statistics [-] Medicare Home Health Agency$",
    cms_hospice             = "^CMS Program Statistics [-] Medicare Hospice$",
    cms_inpatient           = "^CMS Program Statistics [-] Medicare Inpatient Hospital$",
    cms_new_enroll          = "^CMS Program Statistics [-] Medicare Newly Enrolled$",
    cms_outpatient          = "^CMS Program Statistics [-] Medicare Outpatient Facility$",
    cms_tos                 = "^CMS Program Statistics [-] Medicare Part A [&] Part B [-] All Types of Service$",
    cms_partd               = "^CMS Program Statistics [-] Medicare Part D$",
    cms_partd_enroll        = "^CMS Program Statistics [-] Medicare Part D Enrollment$",
    cms_phys_npp_supp       = "^CMS Program Statistics [-] Medicare Physician, Non[-]Physician Practitioner [&] Supplier$",
    cms_premiums            = "^CMS Program Statistics [-] Medicare Premiums$",
    cms_providers           = "^CMS Program Statistics [-] Medicare Providers$",
    cms_snf                 = "^CMS Program Statistics [-] Medicare Skilled Nursing Facility$",
    cms_total_enroll        = "^CMS Program Statistics [-] Medicare Total Enrollment$",
    cms_dual_enroll         = "^CMS Program Statistics [-] Medicare[-]Medicaid Dual Enrollment$",
    cms_orig_enroll         = "^CMS Program Statistics [-] Original Medicare Enrollment$",
    nhome_mds_facility      = "^Facility-Level Minimum Data Set Frequency$",
    nhome_mds_total         = "^Minimum Data Set Frequency$",
    market_cbsa             = "^Market Saturation [&] Utilization Core[-]Based Statistical Areas$",
    market_state_cnty       = "^Market Saturation [&] Utilization State[-]County$",
    partb_drug_discard      = "^Medicare Part B Discarded Drug Units$",
    partb_drug_spend        = "^Medicare Part B Spending by Drug$",
    partd_drug_spend        = "^Medicare Part D Spending by Drug$",
    partd_opioid            = "^Medicare Part D Opioid Prescribing Rates [-] by Geography$",
    bene_survey_covid       = "^Medicare Current Beneficiary Survey [-] COVID-19 Supplement$",
    bene_survey_cost        = "^Medicare Current Beneficiary Survey [-] Cost Supplement$",
    bene_survey_file        = "^Medicare Current Beneficiary Survey [-] Survey File$",
    geovar_adv              = "^Medicare Advantage Geographic Variation [-] National [&] State$",
    geovar_hrr              = "^Medicare Geographic Variation [-] by Hospital Referral Region$",
    geovar_nsc              = "^Medicare Geographic Variation [-] by National, State [&] County$",
    pdp_month               = "^Monthly Prescription Drug Plan Formulary and Pharmacy Network Information$",
    pdp_quarter             = "^Quarterly Prescription Drug Plan Formulary, Pharmacy Network, and Pricing Information$",
    hha_owners              = "^Home Health Agency All Owners$",
    hha_costreport          = "^Home Health Agency Cost Report$",
    hha_enrollments         = "^Home Health Agency Enrollments$",
    hospice_owners          = "^Hospice All Owners$",
    hospice_enrollments     = "^Hospice Enrollments$",
    hospice_acute           = "^Medicare Post[-]Acute Care and Hospice [-] by Geography [&] Provider",
    hospital_transparency   = "^Hospital Price Transparency Enforcement Activities and Outcomes$",
    hospital_owners         = "^Hospital All Owners$",
    hospital_chow           = "^Hospital Change of Ownership$",
    hospital_chow_owner     = "^Hospital Change of Ownership - Owner Information$",
    hospital_enrollments    = "^Hospital Enrollments$",
    hospital_costreport     = "^Hospital Provider Cost Report",
    hospital_service_area   = "^Hospital Service Area",
    rhc_owners              = "^Rural Health Clinic All Owners$",
    rhc_enrollments         = "^Rural Health Clinic Enrollments$",
    fqhc_owners             = "^Federally Qualified Health Center All Owners$",
    fqhc_enrollments        = "^Federally Qualified Health Center Enrollments$",
    pilat_non_physician     = "^Pending Initial Logging and Tracking Non Physicians$",
    pilat_physician         = "^Pending Initial Logging and Tracking Physicians$",
    revalid_group           = "^Revalidation Clinic Group Practice Reassignment$",
    revalid_due             = "^Revalidation Due Date List$",
    revalid_list            = "^Revalidation Reassignment List$",
    snf_owners              = "^Skilled Nursing Facility All Owners$",
    snf_chow                = "^Skilled Nursing Facility Change of Ownership$",
    snf_chow_owner          = "^Skilled Nursing Facility Change of Ownership [-] Owner Information$",
    snf_cost_report         = "^Skilled Nursing Facility Cost Report$",
    snf_enrollments         = "^Skilled Nursing Facility Enrollments$"
    ),
  temporal = list(
    quality_payment         = "^Quality Payment Program Experience$",
    procedure_summary       = "^Physician[/]Supplier Procedure Summary$",
    dialysis_facility       = "^Medicare Dialysis Facilities$",
    aco_shared_savings      = "^Performance Year Financial and Quality Results$",
    opioid_treatment        = "^Opioid Treatment Program Providers$",
    hospital_costreport     = "^Hospital Provider Cost Report$",
    snf_costreport          = "^Skilled Nursing Facility Cost Report$",
    hha_costreport          = "^Home Health Agency Cost Report$",
    nhome_performance       = "^Nursing Home Affiliated Entity Performance Measures$",
    nhome_mds_frequency     = "^Minimum Data Set Frequency$",
    nhome_mds_facility      = "^Facility[-]Level Minimum Data Set Frequency$",
    inpatient_geography     = "^Medicare Inpatient Hospitals [-] by Geography and Service$",
    inpatient_provider      = "^Medicare Inpatient Hospitals [-] by Provider$",
    inpatient_service       = "^Medicare Inpatient Hospitals [-] by Provider and Service$",
    outpatient_geography    = "^Medicare Outpatient Hospitals [-] by Geography and Service$",
    outpatient_service      = "^Medicare Outpatient Hospitals [-] by Provider and Service$",
    prx_geography           = "^Medicare Part D Prescribers [-] by Geography and Drug$",
    prx_provider            = "^Medicare Part D Prescribers [-] by Provider$",
    prx_drug                = "^Medicare Part D Prescribers [-] by Provider and Drug$",
    dme_geography           = "^Medicare Durable Medical Equipment, Devices [&] Supplies [-] by Geography and Service$",
    dme_provider            = "^Medicare Durable Medical Equipment, Devices [&] Supplies [-] by Referring Provider$",
    dme_service             = "^Medicare Durable Medical Equipment, Devices [&] Supplies [-] by Referring Provider and Service$",
    dme_supplier            = "^Medicare Durable Medical Equipment, Devices [&] Supplies [-] by Supplier$",
    dme_supplier_service    = "^Medicare Durable Medical Equipment, Devices [&] Supplies [-] by Supplier and Service$",
    nhome_staff_nonurse     = "^Payroll Based Journal Daily Non[-]Nurse Staffing$",
    nhome_staff_nurse       = "^Payroll Based Journal Daily Nurse Staffing$",
    nhome_staff_employee    = "^Payroll Based Journal Employee Detail Nursing Home Staffing$",
    util_geography          = "^Medicare Physician [&] Other Practitioners [-] by Geography and Service$",
    util_provider           = "^Medicare Physician [&] Other Practitioners [-] by Provider$",
    util_service            = "^Medicare Physician [&] Other Practitioners [-] by Provider and Service$"
    ),
  group = list(
    care_hha                = list(group = "Home Health Agencies", alias = c("hha_owners", "hha_cost_report", "hha_enrollments")),
    care_hospice            = list(group = "Hospices", alias = c("hospice_owners", "hospice_enrollments", "hospice_acute")),
    care_hospital           = list(group = "Hospitals", alias = c("hospital_owners", "hospital_chow", "hospital_chow_owner", "hospital_enrollments", "hospital_cost_report", "hospital_service_area")),
    rhc                     = list(group = "Rural Health Clinics", alias = c("rhc_owners", "rhc_enrollments")),
    fqhc                    = list(group = "Federally Qualified Health Centers", alias = c("fqhc_owners", "fqhc_enrollments")),
    pending                 = list(group = "Pending Initial Logging and Tracking", alias = c("pilat_non_physician", "pilat_physician")),
    reassignment            = list(group = "Revalidation Reassignment Lists", alias = c("revalid_group", "revalid_due", "revalid_list")),
    care_snf                = list(group = "Skilled Nursing Facilities", alias = c("snf_owners", "snf_chow", "snf_chow_owner", "snf_cost_report", "snf_enrollments")),
    care_aco                = list(group = "Accountable Care Organizations", alias = c("aco_reach_aligned", "aco_reach_eligible", "aco_reach_results", "aco_reach_providers", "aco_reach_orgs", "aco_pioneer", "aco_participants", "aco_snf_affiliate", "aco_organizations", "aco_bene_cnty")),
    cms_stats               = list(group = "CMS Program Statistics", alias = c("cms_ma_enroll", "cms_ma_outpatient", "cms_ma_other", "cms_ma_inpatient", "cms_ma_snf", "cms_deaths", "cms_hha", "cms_hospice", "cms_inpatient", "cms_new_enroll", "cms_outpatient", "cms_tos", "cms_partd","cms_partd_enroll", "cms_phys_npp_supp", "cms_premiums", "cms_providers", "cms_snf", "cms_total_enroll", "cms_dual_enroll", "cms_orig_enroll")),
    care_caid               = list(group = "Medicaid", alias = c("care_caid_managed_care", "care_caid_opioid_geo", "care_caid_drug_spend")),
    care_geovar             = list(group = "Medicare Geographic Variation", alias = c("geovar_adv", "geovar_hrr", "geovar_nsc")),
    care_pdp                = list(group = "Prescription Drug Plan Formulary, Pharmacy Network, and Pricing Information", alias = c("pdp_month", "pdp_quarter")),
    bene_survey             = list(group = "Medicare Current Beneficiary Survey", alias = c("bene_survey_covid", "bene_survey_cost", "bene_survey_file")),
    partb_drug              = list(group = "Medicare Part B Drugs", alias = c("partb_drug_discard", "partb_drug_spend")),
    partd_drug              = list(group = "Medicare Part D Drugs", alias = c("partd_opioid", "partd_drug_spend")),
    care_market             = list(group = "Market Saturation & Utilization", alias = c("market_cbsa", "market_state_cnty"))
    ),
  troup = list(
    care_inpatient          = list(group = "Medicare Inpatient Hospitals", alias = c("inpatient_geography", "inpatient_provider", "inpatient_service")),
    care_outpatient         = list(group = "Medicare Outpatient Hospitals", alias = c("outpatient_geography", "outpatient_service")),
    care_prescribers        = list(group = "Medicare Part D Prescribers", alias = c("prx_geography", "prx_provider", "prx_drug")),
    care_dme_suppliers      = list(group = "Medicare Durable Medical Equipment, Devices & Supplies", alias = c("dme_geography", "dme_provider", "dme_service", "dme_supplier", "dme_supplier_service")),
    care_nhome_staff        = list(group = "Nursing Home Payroll-Based Journal Staffing", alias = c("nhome_staff_nonurse", "nhome_staff_nurse", "nhome_staff_employee")),
    care_utilization        = list(group = "Medicare Physician & Other Practitioners", alias = c("util_geography", "util_provider", "util_service")),
    care_nhome              = list(group = "Nursing Home Performance", alias = c("nhome_performance", "nhome_mds_frequency", "nhome_mds_facility"))
    )
)

# ------- caid_list ------
#' @autoglobal
#' @noRd
caid_list <- list(
  endpoint = list(
    aca_ful                       = "ACA Federal Upper Limits",
    caid_drug_rebate              = "Product Data for Newly Reported Drugs in the Medicaid Drug Rebate Program",
    caid_enroll_month             = "Monthly Enrollment - Test",
    caid_enroll_adult             = "Medicaid Enrollment - New Adult Group",
    caid_enterprise               = "Medicaid Enterprise System Datatable",
    caid_pi                       = "PI dataset",
    caid_tiles                    = "category_tiles",
    mlr_summary                   = "MLR Summary Reports",
    managed_longterm              = "Managed Long Term Services and Supports \\(MLTSS\\) Enrollees",
    dsh_requirement               = "Disproportionate Share Hospital \\(DSH\\) Payments [-] Annual Reporting Requirements",
    pharm_release_index           = "Division of Pharmacy Releases Index dataset",
    cahps_nam_puf                 = "NAM CAHPS 2014 Public Use",
    caid_nadac                    = "^NADAC$",
    caid_nadac_first              = "^First Time NADAC Rates$",
    caid_nadac_compare            = "^NADAC Comparison$",
    caid_finance_mgmt             = "Medicaid Financial Management Data$",
    caid_finance_nation           = "Medicaid Financial Management Data National Totals",
    caid_chip_bene_month          = "Program Information for Medicaid and CHIP Beneficiaries by Month",
    caid_chip_bene_year           = "Program Information for Medicaid and CHIP Beneficiaries by Year",
    caid_chip_application         = "^CHIP Applications, Eligibility Determinations, and Enrollment Data",
    caid_chip_continue            = "^Continuous Eligibility for Medicaid and CHIP Coverage$",
    caid_chip_express             = "Express Lane Eligibility for Medicaid and CHIP Coverage",
    caid_chip_metrics             = "Medicaid and CHIP CAA Reporting Metrics",
    caid_chip_levels              = "Medicaid and CHIP Eligibility Levels",
    caid_chip_renewal             = "Medicaid and CHIP Updated Renewal Outcomes",
    caid_chip_presume             = "Presumptive Eligibility for Medicaid and CHIP Coverage",
    caid_chip_separate            = "Separate CHIP Enrollment by Month and State",
    caid_chip_application_state   = "State Medicaid and CHIP Applications, Eligibility Determinations, and Enrollment Data",
    caid_chip_processing_state    = "State Medicaid and CHIP Eligibility Processing Data",
    caid_chip_test                = "State Medicaid and CHIP Test",
    demo_wellvisit                = "^Medicaid and CHIP enrollees who received a well",
    demo_mental                   = "^Medicaid and CHIP enrollees who received mental health or SUD services$",
    demo_disability               = "^Medicaid enrollees who qualify for benefits based on disability$",
    demo_prematurity              = "^Prematurity and severe maternal morbidity among Medicaid",
    demo_language                 = "^Primary language spoken by the Medicaid and CHIP population$",
    demo_ethnicity                = "^Race and ethnicity of the national Medicaid and CHIP population$",
    demo_rural                    = "^Rural Medicaid and CHIP enrollees$",
    demo_waiver                   = "^Section 1915",
    service_acute                 = "^Acute Care Services Provided to the Medicaid and CHIP Population$",
    service_behavior              = "^Behavioral Health Services\\s?Provided to the Medicaid and CHIP Population$",
    service_perinatal             = "^Perinatal Care Services Provided to Medicaid and CHIP Beneficiaries ages 15 to 44",
    service_screening             = "^Health Screenings Provided to Medicaid and CHIP Beneficiaries Under Age 19",
    service_contraceptive         = "^Contraceptive Care Services Provided to Medicaid and CHIP Beneficiaries ages 15 to 44",
    service_dental                = "^Dental Services Provided to Medicaid and CHIP Beneficiaries Under Age 19",
    service_pregnancy             = "^Pregnancy Outcomes for Medicaid and CHIP Beneficiaries ages 15 to 44",
    service_telehealth            = "^Telehealth Services Provided to the Medicaid and CHIP Population",
    service_vaccination           = "^Vaccinations Provided to the Medicaid and CHIP Population under age 19",
    service_bloodlead             = "^Blood Lead Screening Services Provided to Medicaid and CHIP Beneficiaries",
    service_respiratory           = "^Respiratory Conditions in the Medicaid and CHIP Population",
    benes_behavior                = "Beneficiaries receiving a behavioral health service by behavioral health condition, 2017-2021",
    benes_physical                = "Beneficiaries receiving a physical health service among beneficiaries receiving a SUD service by physical health cond, 2017-2021",
    benes_mental                  = "Beneficiaries receiving a physical hlth serv among beneficiaries receiving a mental hlth serv, by physical hlth cond, 2017-2021",
    benes_integrated              = "Beneficiaries who could benefit from integrated care, 2017-2021",
    benes_nas                     = "Number and rate of NAS per 1,000 births in newborns whose deliveries were covered by Medicaid or CHIP, 2017 - 2021",
    benes_smm                     = "Number and rate of SMM among Medicaid- and CHIP-covered deliveries, 2017 - 2021",
    benes_pregnant                = "Number of pregnant and postpartum Medicaid and CHIP beneficiaries, 2017-2021",
    benes_delivery                = "Rate of NAS per 1,000 births in newborns whose deliveries were covered by Medicaid or CHIP, 2017 - 2019",
    benefit_pkg_month             = "Benefit Package for Medicaid and CHIP Beneficiaries by Month",
    benefit_pkg_year              = "Benefit Package for Medicaid and CHIP Beneficiaries by Year",
    drug_amp_month                = "Drug AMP Reporting - Monthly",
    drug_amp_quarter              = "Drug AMP Reporting - Quarterly",
    drug_products                 = "Drug Products in the Medicaid Drug Rebate Program",
    drug_clot                     = "^Clotting Factor Drug Report",
    drug_pediatric                = "Exclusive Pediatric Drugs",
    drug_contact_manu             = "Drug Manufacturer Contacts",
    drug_contact_state            = "Medicaid Drug Rebate Program State Contact Information",
    dual_status_month             = "Dual Status Information for Medicaid and CHIP Beneficiaries by Month",
    dual_status_year              = "Dual Status Information for Medicaid and CHIP Beneficiaries by Year",
    meg_month                     = "Major Eligibility Group Information for Medicaid and CHIP Beneficiaries by Month",
    meg_year                      = "Major Eligibility Group Information for Medicaid and CHIP Beneficiaries by Year",
    cms64_caa                     = "Medicaid CMS-64 CAA 2023 Increased FMAP Expenditure Data Collected through MBES/CBES",
    cms64_ffcra                   = "Medicaid CMS-64 FFCRA Increased FMAP Expenditure",
    cms64_adult                   = "Medicaid CMS-64 New Adult Group Expenditures",
    managed_care_summary          = "Managed Care Enrollment Summary",
    managed_care_program_state    = "^Managed Care Programs\\sby\\sState$",
    managed_care_program_plan     = "Managed Care Enrollment by Program and Plan",
    managed_care_program_pop_all  = "Managed Care Enrollment by Program and Population \\(All\\)",
    managed_care_program_pop_dual = "Managed Care Enrollment by Program and Population \\(Duals\\)",
    managed_care_feat_pop         = "Managed Care Features By Enrollment Population",
    managed_care_feat_qa          = "Managed Care Features by QA and Performance Incentive",
    managed_care_bene_month       = "Managed Care Information for Medicaid and CHIP Beneficiaries by Month",
    managed_care_bene_year        = "Managed Care Information for Medicaid and CHIP Beneficiaries by Year",
    managed_care_share            = "Share of Medicaid Enrollees in Managed Care",
    unwind_marketplace            = "HealthCare\\.gov Marketplace Medicaid Unwinding Report",
    unwind_transition             = "HealthCare\\.gov Transitions Marketplace Medicaid Unwinding Report",
    unwind_historic               = "Separate CHIP Enrollment by Month and State\\sHistoric CAA/Unwinding Period",
    unwind_sbm                    = "State-based Marketplace \\(SBM\\) Medicaid Unwinding Report"
  ),
  temporal = list(
    nadac_year                    = "^NADAC$",
    managed_care_state            = "^Managed Care Programs by State$",
    caid_drug_rebate_week         = "^Product Data for Newly Reported Drugs in the Medicaid Drug Rebate Program$",
    blood_disorder                = "^Pricing Comparison for Blood Disorder Treatments$",
    state_drug_util               = "^State Drug Utilization Data$",
    healthcare_quality            = "^Child and Adult Health Care Quality Measures$"
  ),
  group = list(
    caid_demographics = list(
      group = "Medicaid and CHIP Enrollee Demographics",
      alias = c(
        "demo_wellvisit",
        "demo_mental",
        "demo_disability",
        "demo_prematurity",
        "demo_language",
        "demo_ethnicity",
        "demo_rural",
        "demo_waiver"
      )
    ),
    caid_services = list(
      group = "Services Provided to the Medicaid and CHIP Population",
      alias = c(
        "service_acute",
        "service_behavior",
        "service_perinatal",
        "service_screening",
        "service_contraceptive",
        "service_dental",
        "service_pregnancy",
        "service_telehealth",
        "service_vaccination",
        "service_bloodlead",
        "service_respiratory"
      )
    ),
    caid_benes = list(
      group = "Beneficiaries Receiving A Service",
      alias = c(
        "benes_behavior",
        "benes_physical",
        "benes_mental",
        "benes_integrated",
        "benes_nas",
        "benes_smm",
        "benes_pregnant",
        "benes_delivery"
      )
    ),
    caid_finance = list(
      group = "Medicaid Financial Management Data",
      alias = c(
        "caid_finance_mgmt",
        "caid_finance_nation"
      )
    ),
    caid_nadac_group = list(
      group = "NADAC (National Average Drug Acquisition Cost)",
      alias = c(
        "caid_nadac",
        "caid_nadac_first",
        "caid_nadac_compare"
      )
    ),
    caid_benefit_pkg = list(
      group = "Benefit Package for Medicaid and CHIP Beneficiaries",
      alias = c(
        "benefit_pkg_month",
        "benefit_pkg_year"
      )
    ),
    caid_drug = list(
      group = "Medicaid Drug Datasets",
      alias = c(
        "drug_amp_mon",
        "drug_amp_qtr",
        "drug_products",
        "drug_clot",
        "drug_pediatric",
        "drug_contact_manu",
        "drug_contact_state"
      )
    ),
    caid_dual_status = list(
      group = "Dual Status Information for Medicaid and CHIP Beneficiaries",
      alias = c(
        "dual_status_month",
        "dual_status_year"
      )
    ),
    caid_meg = list(
      group = "Major Eligibility Group Information for Medicaid and CHIP Beneficiaries",
      alias = c(
        "meg_month",
        "meg_year"
      )
    ),
    caid_cms64 = list(
      group = "Medicaid CMS-64",
      alias = c(
        "cms64_caa",
        "cms64_ffcra",
        "cms64_adult"
      )
    ),
    caid_managed_care = list(
      group = "Medicaid Managed Care Enrollment",
      alias = c(
        "managed_care_summary",
        "managed_care_program_state",
        "managed_care_program_plan",
        "managed_care_program_pop_all",
        "managed_care_program_pop_dual",
        "managed_care_feat_pop",
        "managed_care_feat_qa",
        "managed_care_bene_month",
        "managed_care_bene_year"
      )
    ),
    caid_unwind = list(
      group = "Medicaid Unwinding Report",
      alias = c(
        "unwind_marketplace",
        "unwind_transition",
        "unwind_historic",
        "unwind_sbm"
      )
    )
  )
)

# ------- open_list ------
#' @autoglobal
#' @noRd
open_list <- list(
  endpoint = list(
    profile_covered               = "^Covered Recipient Profile Supplement$",
    profile_physician             = "^Physician \\(Distinct\\) Profile Information$",
    profile_information           = "^Profile Information$",
    profile_mapping               = "^Provider Profile ID Mapping Table$",
    profile_entity                = "^Reporting Entity Profile Information$",
    profile_teaching              = "^Teaching Hospital Profile Information$",
    summary_dashboard             = "^Summary Dashboard",
    summary_state                 = "^State Level Payment Total and Averages for all Years$",
    summary_nature                = "^State Payment Totals and Averages Grouped by Nature of Payment for all Years$",
    summary_national              = "^National Level Payment Total and Averages for all Years$",
    summary_specialty             = "^National Level Payment Total and Averages by Provider Specialty for all Years$"
  ),
  temporal = list(
    payment_general               = "^General Payment Data$",
    payment_ownership             = "^Ownership Payment Data$",
    payment_research              = "^Research Payment Data$",
    grouped_covered_nature        = "^Payments Grouped by Covered Recipient and Nature of Payments$",
    grouped_covered_entity        = "^Payments Grouped by Covered Recipient and Reporting Entities$",
    grouped_entity_nature         = "^Payments Grouped by Reporting Entities and Nature of Payments$",
    grouped_entity_covered_nature = "^Payments Grouped by Reporting Entities, Covered Recipient, and Nature of Payments$",
    grouped_state_nature          = "^State Payment Totals Grouped by Nature of Payment for all Years$"
  ),
  group = list(
    profile                       = list(group = "Open Payments Profiles", alias = c("profile_covered", "profile_physician", "profile_information", "profile_mapping", "profile_entity", "profile_teaching")),
    summary                       = list(group = "Open Payments Summaries", alias = c("summary_dashboard", "summary_state", "summary_nature", "summary_national", "summary_specialty"))),
  troup = list(
    payment_grouped               = list(group = "Open Payments by Year (Grouped)", alias = c("grouped_covered_nature", "grouped_covered_entity", "grouped_entity_nature", "grouped_entity_covered_nature", "grouped_state_nature")),
    payment_detailed              = list(group = "Open Payments by Year (Detailed)", alias = c("payment_general", "payment_ownership", "payment_research")))
)

# ------- pro_list ------
#' @autoglobal
#' @noRd
pro_list <- list(
  endpoint = list(
    asc_facility              = "^Ambulatory Surgical Center Quality Measures [-] Facility",
    asc_national              = "^Ambulatory Surgical Center Quality Measures [-] National",
    asc_state                 = "^Ambulatory Surgical Center Quality Measures [-] State",
    cahps_hospice_nation      = "^Hospice care [-] National CAHPS Hospice Survey Data$",
    cahps_hospice_provider    = "^Hospice care [-] Provider CAHPS Hospice Survey Data$",
    cahps_hospice_state       = "^Hospice care [-] State CAHPS Hospice Survey Data$",
    cahps_hhc_patient         = "^Home Health Care [-] Patient Survey \\(HHCAHPS\\) 2023Q4 to 2024Q3$",
    cahps_hhc_measure         = "^Home Health Care [-] Patient Survey \\(HHCAHPS\\) Measure Dates 2023Q4 to 2024Q3$",
    cahps_hhc_national        = "^Home Health Care [-] Patient Survey \\(HHCAHPS\\) National Data 2023Q4 to 2024Q3$",
    cahps_hhc_state           = "^Home Health Care [-] Patient Survey \\(HHCAHPS\\) State Data 2023Q4 to 2024Q3$",
    cahps_ich_esrd            = "^ESRD QIP [-] In[-]Center Hemodialysis Consumer Assessment Of Healthcare Providers And Services Systems \\(ICH CAHPS\\) Survey",
    cahps_ich_facility        = "^Patient survey \\(ICH CAHPS\\) [-] Facility$",
    cahps_ich_national        = "^Patient survey \\(ICH CAHPS\\) [-] National$",
    cahps_ich_state           = "^Patient survey \\(ICH CAHPS\\) [-] State$",
    cahps_oas_footnotes       = "^Outpatient and Ambulatory Surgery Consumer Assessment of Healthcare Providers and Systems \\(OAS CAHPS\\) survey [-] Footnotes",
    cahps_oas_asc_facility    = "^Outpatient and Ambulatory Surgery Consumer Assessment of Healthcare Providers and Systems \\(OAS CAHPS\\) survey for ambulatory surgical centers [-] Facility",
    cahps_oas_asc_national    = "^Outpatient and Ambulatory Surgery Consumer Assessment of Healthcare Providers and Systems \\(OAS CAHPS\\) survey for ambulatory surgical centers [-] National",
    cahps_oas_asc_state       = "^Outpatient and Ambulatory Surgery Consumer Assessment of Healthcare Providers and Systems \\(OAS CAHPS\\) survey for ambulatory surgical centers [-] State",
    cahps_oas_hosp_facility   = "^Outpatient and Ambulatory Surgery Consumer Assessment of Healthcare Providers and Systems \\(OAS CAHPS\\) survey for hospital outpatient departments [-] Facility",
    cahps_oas_hosp_national   = "^Outpatient and Ambulatory Surgery Consumer Assessment of Healthcare Providers and Systems \\(OAS CAHPS\\) survey for hospital outpatient departments [-] National",
    cahps_oas_hosp_state      = "^Outpatient and Ambulatory Surgery Consumer Assessment of Healthcare Providers and Systems \\(OAS CAHPS\\) survey for hospital outpatient departments [-] State",
    hcahps_pch_hospital       = "Patient Survey \\(PCH [-] HCAHPS\\) PPS[-]Exempt Cancer Hospital [-] Hospital",
    hcahps_pch_national       = "Patient Survey \\(PCH [-] HCAHPS\\) PPS[-]Exempt Cancer Hospital [-] National",
    hcahps_pch_state          = "Patient Survey \\(PCH [-] HCAHPS\\) PPS[-]Exempt Cancer Hospital [-] State",
    hcahps_hospital           = "Patient survey \\(HCAHPS\\) [-] Hospital",
    hcahps_national           = "Patient survey \\(HCAHPS\\) [-] National",
    hcahps_state              = "Patient survey \\(HCAHPS\\) [-] State",
    complication_hospital     = "^Complications and Deaths [-] Hospital",
    complication_national     = "^Complications and Deaths [-] National",
    complication_state        = "^Complications and Deaths [-] State",
    complication_pch_hospital = "^Complications and Unplanned Hospital Visits [-] PPS-Exempt Cancer Hospital [-] Hospital",
    complication_pch_national = "^Complications and Unplanned Hospital Visits [-] PPS-Exempt Cancer Hospital [-] National",
    dialysis_facility         = "^Dialysis Facility [-] Listing by Facility$",
    dialysis_national         = "^Dialysis Facility [-] National Averages$",
    dialysis_state            = "^Dialysis Facility [-] State Averages$",
    esrd_depression           = "^ESRD QIP [-] Clinical Depression Screening and Follow-up",
    esrd_complete             = "^ESRD QIP [-] Complete QIP Data",
    esrd_adequacy             = "^ESRD QIP [-] Dialysis Adequacy",
    esrd_footnotes            = "^ESRD QIP [-] Footnotes",
    esrd_hypercalcemia        = "^ESRD QIP [-] Hypercalcemia",
    esrd_medication           = "^ESRD QIP [-] Medication Reconciliation",
    esrd_infection            = "^ESRD QIP [-] NHSN Bloodstream Infection",
    esrd_event                = "^ESRD QIP [-] NHSN Dialysis Event Measure",
    esrd_waitlist             = "^ESRD QIP [-] Percentage of Prevalent Patients Waitlisted",
    esrd_hospitalization      = "^ESRD QIP [-] Standardized Hospitalization Ratio",
    esrd_readmission          = "^ESRD QIP [-] Standardized Readmission Ratio",
    esrd_transfusion          = "^ESRD QIP [-] Standardized Transfusion Ratio",
    esrd_performance          = "^ESRD QIP [-] Total Performance Scores",
    esrd_ultrafiltration      = "^ESRD QIP [-] Ultrafiltration Rate",
    esrd_vascular             = "^ESRD QIP [-] Vascular Access Topic",
    hai_hospital              = "^Healthcare Associated Infections [-] Hospital",
    hai_national              = "^Healthcare Associated Infections [-] National",
    hai_state                 = "^Healthcare Associated Infections [-] State",
    hai_pch                   = "^Safety and Healthcare[-]Associated Infection Measures [-] PPS[-]Exempt Cancer Hospital",
    he_hospital               = "^Health Equity [-] Hospital",
    he_national               = "^Health Equity [-] National",
    he_state                  = "^Health Equity [-] State",
    hhc_range                 = "^Home Health Care [-] Measure Date Range$",
    hhc_national              = "^Home Health Care [-] National Data$",
    hhc_state                 = "^Home Health Care [-] State by State Data$",
    hhc_zip                   = "^Home Health Care [-] Zip Codes$",
    hhc_agency                = "^Home Health Care Agencies$",
    hhvbp_agency              = "^Expanded Home Health Value-Based Purchasing \\(HHVBP\\) Model [-] Agency Data$",
    hhvbp_cohort              = "^Expanded Home Health Value-Based Purchasing \\(HHVBP\\) Model [-] Cohort Data$",
    hvbp_outcomes             = "^Hospital Value[-]Based Purchasing \\(HVBP\\) [-] Clinical Outcomes Domain Scores",
    hvbp_efficiency           = "^Hospital Value[-]Based Purchasing \\(HVBP\\) [-] Efficiency Scores",
    hvbp_engagement           = "^Hospital Value[-]Based Purchasing \\(HVBP\\) [-] Person and Community Engagement Domain Scores \\(HCAHPS\\)",
    hvbp_safety               = "^Hospital Value[-]Based Purchasing \\(HVBP\\) [-] Safety",
    hvbp_performance          = "^Hospital Value[-]Based Purchasing \\(HVBP\\) [-] Total Performance Score",
    hospice_general           = "^Hospice [-] General Information$",
    hospice_provider          = "^Hospice [-] Provider Data$",
    hospice_state             = "^Hospice [-] State Data$",
    hospice_zip               = "^Hospice [-] Zip Data$",
    hospice_national          = "^Hospice[-]National Data$",
    hospital_psi90            = "^CMS Medicare PSI[-]90 and component measures [-] six[-]digit estimate dataset",
    hospital_joint            = "^Comprehensive Care For Joint Replacement Model [-] Provider Data",
    hospital_footnote         = "^Footnote Crosswalk",
    hospital_update           = "^Data Updates",
    hospital_dates            = "^Measure Dates",
    hospital_maternal         = "^Maternal Health [-] Hospital",
    hospital_outcomes         = "^Patient[-]Reported Outcomes [-] Hospital",
    hospital_general          = "^Hospital General Information",
    hospital_pi               = "^Promoting Interoperability [-] Hospital",
    hospital_voc_nation       = "^Value of care [-] National",
    hospital_voc_hosp         = "^Payment and value of care [-] Hospital",
    hospital_pmt_state        = "^Payment [-] State",
    hospital_pmt_nation       = "^Payment [-] National",
    hospital_drg_net          = "^Table 1[:] FY2021 Net Change in Base Operating DRG Payment Amount",
    hospital_drg_dist         = "^Table 2[:] FY2021 Distribution of Net Change in Base Operating DRG Payment Amount",
    hospital_pmt_pct          = "^Table 3[:] FY2021 Percent Change in Medicare Payments",
    hospital_pmt_vbi          = "^Table 4[:] FY2021 Value-Based Incentive Payment Amount",
    ipf_national              = "^Inpatient Psychiatric Facility Quality Measure Data [-] National",
    ipf_facility              = "^Inpatient Psychiatric Facility Quality Measure Data [-] by Facility",
    ipf_state                 = "^Inpatient Psychiatric Facility Quality Measure Data [-] by State",
    irf_conditions            = "^Inpatient Rehabilitation Facility [-] Conditions$",
    irf_general               = "^Inpatient Rehabilitation Facility [-] General Information$",
    irf_provider              = "^Inpatient Rehabilitation Facility [-] Provider Data$",
    irf_national              = "^Inpatient Rehabilitation Facility [-] National Data$",
    ltch_general              = "^Long-Term Care Hospital [-] General Information$",
    ltch_provider             = "^Long-Term Care Hospital [-] Provider Data$",
    ltch_national             = "^Long-Term Care Hospital [-] National Data$",
    mips_performance          = "^PY 2022 Clinician Public Reporting[:] Overall MIPS Performance$",
    mips_patient              = "^PY 2022 Group Public Reporting[:] Patient Experience$",
    mips_clinician            = "^PY 2022 Clinician Public Reporting[:] MIPS Measures and Attestations$",
    mips_group                = "^PY 2022 Group Public Reporting[:] MIPS Measures and Attestations$",
    mips_virtual              = "^PY 2022 Virtual Group Public Reporting[:] MIPS Measures and Attestations$",
    mspb_claim                = "^Medicare Hospital Spending by Claim",
    mspb_hospital             = "^Medicare Spending Per Beneficiary [-] Hospital$",
    mspb_decimal              = "^Medicare Spending Per Beneficiary [-] Hospital Additional Decimal Places$",
    mspb_national             = "^Medicare Spending Per Beneficiary [-] National$",
    mspb_state                = "^Medicare Spending Per Beneficiary [-] State$",
    nursing_ownership         = "^Ownership$",
    nursing_penalties         = "^Penalties$",
    nursing_provider          = "^Provider Information$",
    nursing_citation          = "^Citation Code Look[-]up$",
    nursing_fire              = "^Fire Safety Deficiencies$",
    nursing_deficiencies      = "^Health Deficiencies$",
    nursing_inspection        = "^Inspection Dates$",
    nursing_quality_mds       = "^MDS Quality Measures$",
    nursing_quality_claims    = "^Medicare Claims Quality Measures$",
    nursing_state_avg         = "^State US Averages$",
    nursing_state_cut         = "^State-Level Health Inspection Cut Points$",
    nursing_interval          = "^Nursing Home Data Collection Interval",
    out_img_hospital          = "^Outpatient Imaging Efficiency [-] Hospital",
    out_img_national          = "^Outpatient Imaging Efficiency [-] National",
    out_img_state             = "^Outpatient Imaging Efficiency [-] State",
    pch_pall_hospital         = "^Palliative Care [-] PPS-Exempt Cancer Hospital [-] Hospital",
    pch_pall_national         = "^Palliative Care [-] PPS-Exempt Cancer Hospital [-] National",
    pdc_affiliations          = "^Facility Affiliation Data$",
    pdc_clinicians            = "^National Downloadable File$",
    pdc_utilization           = "^Utilization Data$",
    reduction_hac             = "Hospital[-]Acquired Condition \\(HAC\\) Reduction Program",
    reduction_hrr             = "Hospital Readmissions Reduction Program",
    snf_vbp_performance       = "^FY 2025 SNF VBP Aggregate Performance$",
    snf_vbp_facility          = "^FY 2025 SNF VBP Facility[-]Level Dataset$",
    snf_quality_nation        = "^Skilled Nursing Facility Quality Reporting Program [-] National Data$",
    snf_quality_provider      = "^Skilled Nursing Facility Quality Reporting Program [-] Provider Data$",
    snf_quality_swing         = "^Skilled Nursing Facility Quality Reporting Program [-] Swing Beds [-] Provider Data$",
    supplier_directory        = "^Medical Equipment Suppliers$",
    timely_hospital           = "^Timely and Effective Care [-] Hospital",
    timely_national           = "^Timely and Effective Care [-] National",
    timely_state              = "^Timely and Effective Care [-] State",
    unplan_hospital           = "^Unplanned Hospital Visits [-] Hospital",
    unplan_national           = "^Unplanned Hospital Visits [-] National",
    unplan_state              = "^Unplanned Hospital Visits [-] State",
    va_behavioral             = "^Veterans Health Administration Behavioral Health Data",
    va_provider               = "^Veterans Health Administration Provider Level Data",
    va_timely                 = "^Veterans Health Administration Timely and Effective Care Data"
  ),
  group = list(
    pro_cahps_spice           = list(group = "CAHPS Hospice Survey Data", alias = c("cahps_hospice_nation", "cahps_hospice_provider", "cahps_hospice_state")),
    pro_cahps_hhc             = list(group = "Home Health Care Patient Survey Data (HHCAHPS)", alias = c("cahps_hhc_patient", "cahps_hhc_measure", "cahps_hhc_national", "cahps_hhc_state")),
    pro_cahps_ich             = list(group = "In-Center Hemodialysis Consumer Assessment Of Healthcare Providers And Services Systems (ICH CAHPS) Survey", alias = c("cahps_ich_esrd", "cahps_ich_facility", "cahps_ich_national", "cahps_ich_state")),
    pro_cahps_oas             = list(group = "Outpatient and Ambulatory Surgery Consumer Assessment of Healthcare Providers and Systems (OAS CAHPS) Survey", alias = c("cahps_oas_footnotes", "cahps_oas_asc_facility", "cahps_oas_asc_national", "cahps_oas_asc_state", "cahps_oas_hosp_facility", "cahps_oas_hosp_national", "cahps_oas_hosp_state")),
    pro_mips                  = list(group = "PY 2022 MIPS Public Reporting", alias = c("mips_performance", "mips_patient", "mips_clinician", "mips_group", "mips_virtual")),
    pro_drs                   = list(group = "Provider Data Catalog", alias = c("pdc_affiliations", "pdc_clinicians", "pdc_utilization")),
    pro_ltch                  = list(group = "Long-Term Care Hospitals", alias = c("ltch_general", "ltch_provider", "ltch_national")),
    pro_irf                   = list(group = "Inpatient Rehabilitation Facilities", alias = c("irf_conditions", "irf_general", "irf_provider", "irf_national")),
    pro_hospice               = list(group = "Hospices", alias = c("hospice_general", "hospice_provider", "hospice_state", "hospice_zip", "hospice_national")),
    pro_hhc_vbp               = list(group = "Expanded Home Health Value-Based Purchasing (HHVBP) Model", alias = c("hhvbp_agency", "hhvbp_cohort")),
    pro_home_health           = list(group = "Home Health Care Agencies", alias = c("hhc_range", "hhc_national", "hhc_state", "hhc_zip", "hhc_agency")),
    pro_snf_vbp               = list(group = "FY 2025 SNF VBP", alias = c("snf_vbp_performance", "snf_vbp_facility")),
    pro_snf_quality           = list(group = "SNF Quality Measures", alias = c("snf_quality_nation", "snf_quality_provider", "snf_quality_swing")),
    pro_nursing               = list(group = "Nursing Homes", alias = c("nursing_ownership", "nursing_penalties", "nursing_provider", "nursing_citation", "nursing_fire", "nursing_deficiencies", "nursing_inspection", "nursing_quality_mds", "nursing_quality_claims", "nursing_state_avg", "nursing_state_cut", "nursing_interval")),
    pro_complication          = list(group = "Complications and Deaths", alias = c("complication_hospital", "complication_state", "complication_national")),
    pro_complication_pch      = list(group = "Complications and Unplanned Hospital Visits: PPS-Exempt Cancer Hospital", alias = c("complication_pch_hospital", "complication_pch_national")),
    pro_asc_quality           = list(group = "Ambulatory Surgical Center Quality Measures", alias = c("asc_facility", "asc_national", "asc_state")),
    pro_equity                = list(group = "Health Equity", alias = c("he_hospital", "he_national", "he_state")),
    pro_hai                   = list(group = "Healthcare Associated Infections", alias = c("hai_hospital", "hai_national", "hai_state", "hai_PCH")),
    pro_dialysis              = list(group = "Dialysis Facilities", alias = c("dialysis_facility", "dialysis_national", "dialysis_state")),
    pro_esrd                  = list(group = "ESRD QIP", alias = c("esrd_depression", "esrd_complete", "esrd_adequacy", "esrd_footnotes", "esrd_hypercalcemia", "esrd_medication", "esrd_infection", "esrd_event", "esrd_waitlist", "esrd_hospitalization", "esrd_readmission", "esrd_transfusion", "esrd_performance", "esrd_ultrafiltration", "esrd_vascular")),
    pro_hvbp                  = list(group = "Hospital Value-Based Purchasing (HVBP)", alias = c("hvbp_outcomes", "hvbp_efficiency", "hvbp_engagement", "hvbp_safety", "hvbp_performance")),
    pro_ipf                   = list(group = "Inpatient Psychiatric Facility Quality Measure Data", alias = c("ipf_national", "ipf_facility", "ipf_state")),
    pro_mspb                  = list(group = "Medicare Spending Per Beneficiary", alias = c("mspb_claim", "mspb_hospital", "mspb_decimal", "mspb_national", "mspb_state")),
    pro_out_img               = list(group = "Outpatient Imaging Efficiency", alias = c("out_img_hospital", "out_img_national", "out_img_state")),
    pro_pch_pall              = list(group = "Palliative Care: PPS-Exempt Cancer Hospital", alias = c("pch_pall_hospital", "pch_pall_national")),
    pro_pch_hcahps            = list(group = "Patient Survey (PCH HCAHPS) PPS-Exempt Cancer Hospital", alias = c("hcahps_pch_hospital", "hcahps_pch_national", "hcahps_pch_state")),
    pro_hcahps                = list(group = "Patient Survey (HCAHPS)", alias = c("hcahps_hospital", "hcahps_national", "hcahps_state")),
    pro_timely                = list(group = "Timely and Effective Care", alias = c("timely_hospital", "timely_national", "timely_state")),
    pro_unplan                = list(group = "Unplanned Hospital Visits", alias = c("unplan_hospital", "unplan_national", "unplan_state")),
    pro_va                    = list(group = "Veterans Health Administration", alias = c("va_behavioral", "va_provider", "va_timely")),
    pro_hospital_changes      = list(group = "Hospital FY2021 Changes in Payment", alias = c("hospital_drg_net", "hospital_drg_dist", "hospital_pmt_pct", "hospital_pmt_vbi")),
    pro_hospital_voc          = list(group = "Payment and Value of Care", alias = c("hospital_voc_nation", "hospital_voc_hosp", "hospital_pmt_state", "hospital_pmt_nation")),
    pro_reduction             = list(group = "Hospital-Acquired Condition & Readmission Reduction Programs", alias = c("reduction_hac", "reduction_hrr"))
  )
)

# ------- hgov_list ------
#' @autoglobal
#' @noRd
hgov_list <- list(
  endpoint = list(
    ab_registration_completion         = "^AB Registration Completion List$",
    ab_suspension_termination          = "^AB Suspension and Termination List$",
    agent_broker_registration_glossary = "^Agent Broker Registration Tracker Glossary$",
    agent_broker_registration_tracker  = "^Agent Broker Registration Tracker$",
    authority_state                    = "^Marketplace Agent[/]Broker NIPR Valid Lines of Authority[,] by State$",
    auto_pop_file                      = "^Auto[-]population File$",
    benefits_cost_sharing              = "^Benefits and Cost Sharing PUF$",
    business_rules                     = "^Business Rules PUF$",
    catastrophic_plans                 = "^Catastrophic Plans for People with Cancelled Policies$",
    contact_admins                     = "^Helpful Contacts Admins$",
    counties                           = "^Counties$",
    county_service_areas               = "^County Service Areas$",
    direct_enrollment_partners         = "^Direct Enrollment Partners$",
    issuer_partner_lookup              = "^Issuer[_]Partner[_]Lookup$",
    issuer_partner_directory           = "^Issuer Partner Directory [-] Reference Text$",
    issuer_de_partner_directory        = "^Issuer and DE Partner Directory$",
    network_puf                        = "^Network PUF$",
    nipr_valid_authority               = "^NIPR Valid Lines of Authority List$",
    plan_attribute                     = "^Plan Attributes PUF$",
    plan_id_cross                      = "^Plan ID Crosswalk PUF$",
    response_codes                     = "^Response Codes$",
    rolling_draft_ecp                  = "^Rolling Draft ECP List$",
    service_area                       = "^Service Area PUF$",
    slcsp_cnty_zip                     = "^SLCSP [-] County[-]Zip Reference Data$",
    states                             = "^States$",
    qhp_ind_med                        = "^QHP Landscape Individual Market Medical$",
    qhp_ind_dent                       = "^QHP Landscape Individual Market Dental$",
    qhp_shop_med                       = "^QHP Landscape SHOP Market Medical$",
    qhp_shop_dent                      = "^QHP Landscape SHOP Market Dental$",
    qhp_id_shop_med                    = "^QHP Landscape ID SHOP Market Medical$",
    qhp_id_shop_dent                   = "^QHP Landscape ID SHOP Market Dental$",
    qhp_id_ind_dent                    = "^QHP Landscape ID Individual Market Dental$",
    qhp_id_ind_med                     = "^QHP Landscape ID Individual Market Medical$",
    qhp_nm_ind_dent                    = "^QHP Landscape NM Individual Market Dental$",
    qhp_nm_ind_med                     = "^QHP Landscape NM Individual Market Medical$",
    qhp_bus_rule_variables             = "^QHP Landscape Health Plan Business Rule Variables$",
    qhp_py19_shop_med_instruct         = "^QHP PY19 Medical SHOP Landscape Instructions$",
    qhp_py19_ind_med_instruct          = "^QHP PY19 Medical Individual Landscape Instructions$",
    qhp_py19_ind_dent_instruct         = "^QHP PY19 Dental Individual Landscape Instructions$",
    qhp_py18_shop_med_instruct         = "^QHP PY18 Medical SHOP Landscape Instructions$",
    qhp_py18_ind_med_instruct          = "^QHP PY18 Medical Individual Landscape Instructions$",
    qhp_py18_ind_dent_instruct         = "^QHP PY18 Dental Individual Landscape Instructions$",
    local_help                         = "^Find Local Help$"
  ),
  temporal = list(
    medical_loss_ratio     = "^MLR Dataset$",
    qhp_quality_ratings    = "^Quality PUF$",
    hie_benefits_costshare = "^Benefits and Cost Sharing PUF$",
    hie_business_rules     = "^Business Rules PUF$",
    hie_machine_readable   = "^Machine Readable PUF$",
    hie_network            = "^Network PUF$",
    hie_plan_attributes    = "^Plan Attributes PUF$",
    hie_plan_id_crosswalk  = "^Plan ID Crosswalk PUF$",
    hie_rate               = "^Rate PUF$",
    hie_service_area       = "^Service Area PUF$",
    hie_transparency       = "^Transparency in Coverage PUF$"
  )
)

# alias <- list(
#   care = list(endpoint = care_list$endpoint, temporal = care_list$temporal),
#   pro  = list(endpoint = pro_list$endpoint),
#   open = list(endpoint = open_list$endpoint, temporal = open_list$temporal),
#   caid = list(endpoint = caid_list$endpoint, temporal = caid_list$temporal),
#   hgov = list(endpoint = hgov_list$endpoint, temporal = hgov_list$temporal)
# )
