#' @include aka_endpoints.R
NULL

#' @autoglobal
#' @noRd
lookup_factory <- function(...) {
  function(x) {
    grep(
      pattern = x,
      x       = rlang::names2(...),
      perl    = TRUE,
      value   = TRUE
    )
  }
}

#' @autoglobal
#' @noRd
aka_look <- list(
  caid = lookup_factory(the$aka$clg$caid),
  care = lookup_factory(the$aka$clg$care),
  hgov = lookup_factory(the$aka$clg$hgov),
  open = lookup_factory(the$aka$clg$open),
  prov = lookup_factory(the$aka$clg$prov)
)

#' @autoglobal
#' @noRd
entry <- function(name, rex = glue::glue("^{name}_"), title, clog) {
  list(
    list(
      title = title,
      alias = switch(
        clog,
        caid = aka_look$caid(rex),
        care = aka_look$care(rex),
        hgov = aka_look$hgov(rex),
        open = aka_look$open(rex),
        prov = aka_look$prov(rex)
        )
      )
    ) |>
    rlang::set_names(name)
}


#' @autoglobal
#' @noRd
make_col <- function() {

  x <- list()

  x$caid <- cheapr::list_combine(
    entry(name  = "bene",
          title = "Medicaid and CHIP State Profiles",
          clog  = "caid"),
    entry(name  = "demo",
          title = "Medicaid and CHIP Enrollee Demographics",
          clog  = "caid"),
    entry(name  = "service",
          rex   = "^serv_",
          title = "Medicaid and CHIP Population Services",
          clog  = "caid"),
    entry(name  = "finance",
          rex   = "^fin_",
          title = "Medicaid Financial Management",
          clog  = "caid"),
    entry(name  = "nadac",
          title = "NADAC (National Average Drug Acquisition Cost)",
          clog  = "caid"),
    entry(name  = "pkg",
          title = "Benefit Package for Medicaid and CHIP Beneficiaries",
          clog  = "caid"),
    entry(name  = "drug",
          title = "Medicaid Drug Datasets",
          clog  = "caid"),
    entry(name  = "dual",
          title = "Medicaid and CHIP Dual Status Beneficiaries",
          clog  = "caid"),
    entry(name  = "meg",
          title = "Major Eligibility Group Information for Medicaid and CHIP Beneficiaries",
          clog  = "caid"),
    entry(name  = "cms64",
          title = "Medicaid CMS-64",
          clog  = "caid"),
    entry(name  = "managed",
          rex   = "^man_",
          title = "Managed Care Enrollment",
          clog  = "caid"),
    entry(name  = "unwind",
          rex   = "^wind_",
          title = "Medicaid Unwinding Report",
          clog  = "caid"))

  x$open <- cheapr::list_combine(
    entry(name  = "profile",
          rex   = "^prf_",
          title = "Open Payments Profiles",
          clog  = "open"),
    entry(name  = "summary",
          rex   = "^sum_",
          title = "Open Payments Summaries",
          clog  = "open"),
    entry(name  = "pay_group",
          rex   = "^grp_",
          title = "Open Payments by Year (Grouped)",
          clog  = "open"),
    entry(name  = "pay_detail",
          rex   = "^pay_",
          title = "Open Payments by Year (Detailed)",
          clog  = "open"))

  x$prov <- cheapr::list_combine(
    entry(name  = "asc",
          # rex   = "^asc_",
          title = "ASC Quality Measures",
          clog  = "prov"),
    entry(name  = "cahps_hhc",
          # rex   = "^cahps_hhc_",
          title = "HHCAHPS Patient Survey",
          clog  = "prov"),
    entry(name  = "cahps_hosp",
          rex   = "^hcahps_",
          title = "HCAHPS Patient Survey",
          clog  = "prov"),
    entry(name  = "cahps_ich",
          # rex   = "^cahps_ich_",
          title = "ICH CAHPS Survey",
          clog  = "prov"),
    entry(name  = "cahps_oas",
          rex   = "^oas_cahps_",
          title = "OAS CAHPS Survey",
          clog  = "prov"),
    entry(name  = "cahps_spice",
          # rex   = "^cahps_spice_",
          title = "CAHPS Hospice Survey",
          clog  = "prov"),
    entry(name  = "cmp_death",
          rex   = "^comp_",
          title = "Complications and Deaths",
          clog  = "prov"),
    entry(name  = "dialysis",
          rex   = "^dial_",
          title = "Dialysis Facilities",
          clog  = "prov"),
    entry(name  = "esrd",
          # rex   = "^esrd_",
          title = "ESRD QIP",
          clog  = "prov"),
    entry(name  = "hac_hrr",
          rex   = "^reduc_",
          title = "HAC & HRR Programs",
          clog  = "prov"),
    entry(name  = "hai",
          # rex   = "^hai_",
          title = "Healthcare-Associated Infections",
          clog  = "prov"),
    entry(name  = "heq",
          rex   = "^he_",
          title = "Health Equity",
          clog  = "prov"),
    entry(name  = "hhc",
          # rex   = "^hhc_",
          title = "Home Health Care Agencies",
          clog  = "prov"),
    entry(name  = "hhvbp",
          # rex   = "^hhvbp_",
          title = "Home Health Value-Based Purchasing",
          clog  = "prov"),
    entry(name  = "hvbp",
          # rex   = "^hvbp_",
          title = "Hospital Value-Based Purchasing",
          clog  = "prov"),
    entry(name  = "imaging",
          rex   = "^out_img_",
          title = "Outpatient Imaging Efficiency",
          clog  = "prov"),
    entry(name  = "ipf",
          # rex   = "^ipf_",
          title = "Inpatient Psychiatric Facility Quality Measures",
          clog  = "prov"),
    entry(name  = "irf",
          # rex   = "^irf_",
          title = "Inpatient Rehabilitation Facilities",
          clog  = "prov"),
    entry(name  = "ltch",
          # rex   = "^ltch_",
          title = "Long-Term Care Hospitals",
          clog  = "prov"),
    entry(name  = "mips",
          # rex   = "^mips_",
          title = "MIPS Public Reporting",
          clog  = "prov"),
    entry(name  = "mspb",
          # rex   = "^mspb_",
          title = "Medicare Spending Per Beneficiary",
          clog  = "prov"),
    entry(name  = "nh",
          # rex   = "^nh_",
          title = "Nursing Homes",
          clog  = "prov"),
    entry(name  = "pch_comp",
          # rex   = "^pch_comp_",
          title = "Complications/Unplanned Visits (PCH)",
          clog  = "prov"),
    entry(name  = "pch_hcahps",
          # rex   = "^pch_hcahps_",
          title = "HCAHPS (PCH)",
          clog  = "prov"),
    entry(name  = "pch_pall",
          # rex   = "^pch_pall_",
          title = "Palliative Care (PCH)",
          clog  = "prov"),
    entry(name  = "pdc",
          # rex   = "^pdc_",
          title = "Provider Data Catalog",
          clog  = "prov"),
    entry(name  = "snf_vbp",
          # rex   = "^snf_vbp_",
          title = "SNF Value-Based Purchasing",
          clog  = "prov"),
    entry(name  = "snf_qrp",
          # rex   = "^snf_qrp_",
          title = "SNF Quality Measures",
          clog  = "prov"),
    entry(name  = "spice_p",
          rex   = "^spice_",
          title = "Hospices",
          clog  = "prov"),
    entry(name  = "table",
          rex   = "^tbl_",
          title = "Hospital Changes in Payment",
          clog  = "prov"),
    entry(name  = "timely",
          # rex   = "^timely_",
          title = "Timely and Effective Care",
          clog  = "prov"),
    entry(name  = "vets",
          rex   = "^va_",
          title = "Veterans Health Administration",
          clog  = "prov"),
    entry(name  = "visit",
          # rex   = "^visit_",
          title = "Unplanned Hospital Visits",
          clog  = "prov"),
    entry(name  = "voc",
          rex   = "^voc_|^pmt_",
          title = "Payment and Value of Care",
          clog  = "prov"))

  x$care <- cheapr::list_combine(
    entry(name  = "hha",
          # rex   = "^hha_",
          title = "Home Health Agencies",
          clog  = "care"),
    entry(name  = "spice_c",
          rex   = "^spice_",
          title = "Hospices",
          clog  = "care"),
    entry(name  = "hosp",
          # rex   = "^hosp_",
          title = "Hospitals",
          clog  = "care"),
    entry(name  = "rhc",
          # rex   = "^rhc_",
          title = "Rural Health Clinics",
          clog  = "care"),
    entry(name  = "fqhc",
          # rex   = "^fqhc_",
          title = "Federally Qualified Health Centers",
          clog  = "care"),
    entry(name  = "pend",
          rex   = "^pilat_",
          title = "Pending Initial Logging and Tracking",
          clog  = "care"),
    entry(name  = "reval",
          # rex   = "^reval_",
          title = "Revalidation Reassignments",
          clog  = "care"),
    entry(name  = "snf",
          # rex   = "^snf_",
          title = "Skilled Nursing Facilities",
          clog  = "care"),
    entry(name  = "aco",
          # rex   = "^aco_",
          title = "Accountable Care Organizations",
          clog  = "care"),
    entry(name  = "reach",
          # rex   = "^reach_",
          title = "Accountable Care REACH Organizations",
          clog  = "care"),
    entry(name  = "care_caid",
          rex   = "_caid$",
          title = "Medicare Medicaid",
          clog  = "care"),
    entry(name  = "geo",
          # rex   = "^geo_",
          title = "Medicare Geographic Variation",
          clog  = "care"),
    entry(name  = "pdp",
          # rex   = "^pdp_",
          title = "Pharmacy Network/Formulary/Pricing",
          clog  = "care"),
    entry(name  = "bene_surv",
          rex   = "^survey_",
          title = "Medicare Current Beneficiary Survey",
          clog  = "care"),
    entry(name  = "drugb",
          # rex   = "^drugb_",
          title = "Medicare Part B Drugs",
          clog  = "care"),
    entry(name  = "drugd",
          # rex   = "^drugd_",
          title = "Medicare Part D Drugs",
          clog  = "care"),
    entry(name  = "mkt",
          # rex   = "^mkt_",
          title = "Market Saturation & Utilization",
          clog  = "care"),
    entry(name  = "in_hosp",
          rex   = "^in_",
          title = "Medicare Inpatient Hospitals",
          clog  = "care"),
    entry(name  = "out_hosp",
          rex   = "^out_",
          title = "Medicare Outpatient Hospitals",
          clog  = "care"),
    entry(name  = "prx",
          # rex   = "^prx_",
          title = "Medicare Part D Prescribers",
          clog  = "care"),
    entry(name  = "dme",
          # rex   = "^dme_",
          title = "Medicare DME, Devices & Supplies",
          clog  = "care"),
    entry(name  = "pbj",
          # rex   = "^pbj_",
          title = "Nursing Home Payroll-Based Journal Staffing",
          clog  = "care"),
    entry(name  = "util",
          # rex   = "^util_",
          title = "Medicare Physician & Other Practitioners",
          clog  = "care"),
    entry(name  = "mds_nh",
          # rex   = "^mds_nh_",
          title = "Nursing Home Performance",
          clog  = "care"),
    entry(name  = "innovate",
          rex   = "^inno_",
          title = "Innovation Center",
          clog  = "care"))

  x$all <- purrr::list_c(x)
  x$nms <- kit::psort(rlang::names2(x$all), nThread = 4L)
  x$all <- x$all[x$nms]
  x
}
