#' @autoglobal
#' @noRd
select_pro <- function(x, call = caller_env()) {
  x <- switch(
    x,
    asc_facility              = "^Ambulatory Surgical Center Quality Measures [-] Facility",
    asc_national              = "^Ambulatory Surgical Center Quality Measures [-] National",
    asc_state                 = "^Ambulatory Surgical Center Quality Measures [-] State",
    cahps_hospice_nation      = "^Hospice care [-] National CAHPS Hospice Survey Data$",
    cahps_hospice_provider    = "^Hospice care [-] Provider CAHPS Hospice Survey Data$",
    cahps_hospice_state       = "^Hospice care [-] State CAHPS Hospice Survey Data$",
    cahps_hhc_patient         = "^Home Health Care [-] Patient Survey \\(HHCAHPS\\) 2023Q4 to 2024Q3$",
    cahps_hhc_measure         = "^Home Health Care [-] Patient Survey \\(HHCAHPS\\) Measure Dates 2023Q4 to 2024Q3$",
    cahps_hhc_national        = "^Home Health Care [-] Patient Survey \\(HHCAHPS\\) National Data 2023Q4 to 2024Q3$",
    cahps_hhc_state           = "^Home Health Care [-] Patient Survey \\(HHCAHPS\\) State Data 2023Q4 to 2024Q3$",
    cahps_ich_esrd            = "^ESRD QIP [-] In[-]Center Hemodialysis Consumer Assessment Of Healthcare Providers And Services Systems \\(ICH CAHPS\\) Survey",
    cahps_ich_facility        = "^Patient survey \\(ICH CAHPS\\) [-] Facility$",
    cahps_ich_national        = "^Patient survey \\(ICH CAHPS\\) [-] National$",
    cahps_ich_state           = "^Patient survey \\(ICH CAHPS\\) [-] State$",
    cahps_oas_footnotes       = "^Outpatient and Ambulatory Surgery Consumer Assessment of Healthcare Providers and Systems \\(OAS CAHPS\\) survey [-] Footnotes",
    cahps_oas_asc_facility    = "^Outpatient and Ambulatory Surgery Consumer Assessment of Healthcare Providers and Systems \\(OAS CAHPS\\) survey for ambulatory surgical centers [-] Facility",
    cahps_oas_asc_national    = "^Outpatient and Ambulatory Surgery Consumer Assessment of Healthcare Providers and Systems \\(OAS CAHPS\\) survey for ambulatory surgical centers [-] National",
    cahps_oas_asc_state       = "^Outpatient and Ambulatory Surgery Consumer Assessment of Healthcare Providers and Systems \\(OAS CAHPS\\) survey for ambulatory surgical centers [-] State",
    cahps_oas_hosp_facility   = "^Outpatient and Ambulatory Surgery Consumer Assessment of Healthcare Providers and Systems \\(OAS CAHPS\\) survey for hospital outpatient departments [-] Facility",
    cahps_oas_hosp_national   = "^Outpatient and Ambulatory Surgery Consumer Assessment of Healthcare Providers and Systems \\(OAS CAHPS\\) survey for hospital outpatient departments [-] National",
    cahps_oas_hosp_state      = "^Outpatient and Ambulatory Surgery Consumer Assessment of Healthcare Providers and Systems \\(OAS CAHPS\\) survey for hospital outpatient departments [-] State",
    hcahps_pch_hospital       = "Patient Survey \\(PCH [-] HCAHPS\\) PPS[-]Exempt Cancer Hospital [-] Hospital",
    hcahps_pch_national       = "Patient Survey \\(PCH [-] HCAHPS\\) PPS[-]Exempt Cancer Hospital [-] National",
    hcahps_pch_state          = "Patient Survey \\(PCH [-] HCAHPS\\) PPS[-]Exempt Cancer Hospital [-] State",
    hcahps_hospital           = "Patient survey \\(HCAHPS\\) [-] Hospital",
    hcahps_national           = "Patient survey \\(HCAHPS\\) [-] National",
    hcahps_state              = "Patient survey \\(HCAHPS\\) [-] State",
    complication_hospital     = "^Complications and Deaths [-] Hospital",
    complication_national     = "^Complications and Deaths [-] National",
    complication_state        = "^Complications and Deaths [-] State",
    complication_pch_hospital = "^Complications and Unplanned Hospital Visits [-] PPS-Exempt Cancer Hospital [-] Hospital",
    complication_pch_national = "^Complications and Unplanned Hospital Visits [-] PPS-Exempt Cancer Hospital [-] National",
    dialysis_facility         = "^Dialysis Facility [-] Listing by Facility$",
    dialysis_national         = "^Dialysis Facility [-] National Averages$",
    dialysis_state            = "^Dialysis Facility [-] State Averages$",
    esrd_depression           = "^ESRD QIP [-] Clinical Depression Screening and Follow-up",
    esrd_complete             = "^ESRD QIP [-] Complete QIP Data",
    esrd_adequacy             = "^ESRD QIP [-] Dialysis Adequacy",
    esrd_footnotes            = "^ESRD QIP [-] Footnotes",
    esrd_hypercalcemia        = "^ESRD QIP [-] Hypercalcemia",
    esrd_medication           = "^ESRD QIP [-] Medication Reconciliation",
    esrd_infection            = "^ESRD QIP [-] NHSN Bloodstream Infection",
    esrd_event                = "^ESRD QIP [-] NHSN Dialysis Event Measure",
    esrd_waitlist             = "^ESRD QIP [-] Percentage of Prevalent Patients Waitlisted",
    esrd_hospitalization      = "^ESRD QIP [-] Standardized Hospitalization Ratio",
    esrd_readmission          = "^ESRD QIP [-] Standardized Readmission Ratio",
    esrd_transfusion          = "^ESRD QIP [-] Standardized Transfusion Ratio",
    esrd_performance          = "^ESRD QIP [-] Total Performance Scores",
    esrd_ultrafiltration      = "^ESRD QIP [-] Ultrafiltration Rate",
    esrd_vascular             = "^ESRD QIP [-] Vascular Access Topic",
    hai_hospital              = "^Healthcare Associated Infections [-] Hospital",
    hai_national              = "^Healthcare Associated Infections [-] National",
    hai_state                 = "^Healthcare Associated Infections [-] State",
    hai_pch                   = "^Safety and Healthcare[-]Associated Infection Measures [-] PPS[-]Exempt Cancer Hospital",
    he_hospital               = "^Health Equity [-] Hospital",
    he_national               = "^Health Equity [-] National",
    he_state                  = "^Health Equity [-] State",
    hhc_range                 = "^Home Health Care [-] Measure Date Range$",
    hhc_national              = "^Home Health Care [-] National Data$",
    hhc_state                 = "^Home Health Care [-] State by State Data$",
    hhc_zip                   = "^Home Health Care [-] Zip Codes$",
    hhc_agency                = "^Home Health Care Agencies$",
    hhvbp_agency              = "^Expanded Home Health Value-Based Purchasing \\(HHVBP\\) Model [-] Agency Data$",
    hhvbp_cohort              = "^Expanded Home Health Value-Based Purchasing \\(HHVBP\\) Model [-] Cohort Data$",
    hvbp_outcomes             = "^Hospital Value[-]Based Purchasing \\(HVBP\\) [-] Clinical Outcomes Domain Scores",
    hvbp_efficiency           = "^Hospital Value[-]Based Purchasing \\(HVBP\\) [-] Efficiency Scores",
    hvbp_engagement           = "^Hospital Value[-]Based Purchasing \\(HVBP\\) [-] Person and Community Engagement Domain Scores \\(HCAHPS\\)",
    hvbp_safety               = "^Hospital Value[-]Based Purchasing \\(HVBP\\) [-] Safety",
    hvbp_performance          = "^Hospital Value[-]Based Purchasing \\(HVBP\\) [-] Total Performance Score",
    hospice_general           = "^Hospice [-] General Information$",
    hospice_provider          = "^Hospice [-] Provider Data$",
    hospice_state             = "^Hospice [-] State Data$",
    hospice_zip               = "^Hospice [-] Zip Data$",
    hospice_national          = "^Hospice[-]National Data$",
    hospital_PSI90            = "^CMS Medicare PSI[-]90 and component measures [-] six[-]digit estimate dataset",
    hospital_joint            = "^Comprehensive Care For Joint Replacement Model [-] Provider Data",
    hospital_footnote         = "^Footnote Crosswalk",
    hospital_update           = "^Data Updates",
    hospital_dates            = "^Measure Dates",
    hospital_maternal         = "^Maternal Health [-] Hospital",
    hospital_outcomes         = "^Patient[-]Reported Outcomes [-] Hospital",
    hospital_general          = "^Hospital General Information",
    hospital_pi               = "^Promoting Interoperability [-] Hospital",
    hospital_voc_nation       = "^Value of care [-] National",
    hospital_voc_hosp         = "^Payment and value of care [-] Hospital",
    hospital_pmt_state        = "^Payment [-] State",
    hospital_pmt_nation       = "^Payment [-] National",
    hospital_drg_net          = "^Table 1[:] FY2021 Net Change in Base Operating DRG Payment Amount",
    hospital_drg_dist         = "^Table 2[:] FY2021 Distribution of Net Change in Base Operating DRG Payment Amount",
    hospital_pmt_pct          = "^Table 3[:] FY2021 Percent Change in Medicare Payments",
    hospital_pmt_vbi          = "^Table 4[:] FY2021 Value-Based Incentive Payment Amount",
    ipf_national              = "^Inpatient Psychiatric Facility Quality Measure Data [-] National",
    ipf_facility              = "^Inpatient Psychiatric Facility Quality Measure Data [-] by Facility",
    ipf_state                 = "^Inpatient Psychiatric Facility Quality Measure Data [-] by State",
    irf_conditions            = "^Inpatient Rehabilitation Facility [-] Conditions$",
    irf_general               = "^Inpatient Rehabilitation Facility [-] General Information$",
    irf_provider              = "^Inpatient Rehabilitation Facility [-] Provider Data$",
    irf_national              = "^Inpatient Rehabilitation Facility [-] National Data$",
    ltch_general              = "^Long-Term Care Hospital [-] General Information$",
    ltch_provider             = "^Long-Term Care Hospital [-] Provider Data$",
    ltch_national             = "^Long-Term Care Hospital [-] National Data$",
    mips_performance          = "^PY 2022 Clinician Public Reporting[:] Overall MIPS Performance$",
    mips_patient              = "^PY 2022 Group Public Reporting[:] Patient Experience$",
    mips_clinician            = "^PY 2022 Clinician Public Reporting[:] MIPS Measures and Attestations$",
    mips_group                = "^PY 2022 Group Public Reporting[:] MIPS Measures and Attestations$",
    mips_virtual              = "^PY 2022 Virtual Group Public Reporting[:] MIPS Measures and Attestations$",
    mspb_claim                = "^Medicare Hospital Spending by Claim",
    mspb_hospital             = "^Medicare Spending Per Beneficiary [-] Hospital$",
    mspb_decimal              = "^Medicare Spending Per Beneficiary [-] Hospital Additional Decimal Places$",
    mspb_national             = "^Medicare Spending Per Beneficiary [-] National$",
    mspb_state                = "^Medicare Spending Per Beneficiary [-] State$",
    nursing_ownership         = "^Ownership$",
    nursing_penalties         = "^Penalties$",
    nursing_provider          = "^Provider Information$",
    nursing_citation          = "^Citation Code Look[-]up$",
    nursing_fire              = "^Fire Safety Deficiencies$",
    nursing_deficiencies      = "^Health Deficiencies$",
    nursing_inspection        = "^Inspection Dates$",
    nursing_quality_mds       = "^MDS Quality Measures$",
    nursing_quality_claims    = "^Medicare Claims Quality Measures$",
    nursing_state_avg         = "^State US Averages$",
    nursing_state_cut         = "^State-Level Health Inspection Cut Points$",
    nursing_interval          = "^Nursing Home Data Collection Interval",
    out_img_hospital          = "^Outpatient Imaging Efficiency [-] Hospital",
    out_img_national          = "^Outpatient Imaging Efficiency [-] National",
    out_img_state             = "^Outpatient Imaging Efficiency [-] State",
    pch_pall_hospital         = "^Palliative Care [-] PPS-Exempt Cancer Hospital [-] Hospital",
    pch_pall_national         = "^Palliative Care [-] PPS-Exempt Cancer Hospital [-] National",
    pdc_affiliations          = "^Facility Affiliation Data$",
    pdc_clinicians            = "^National Downloadable File$",
    pdc_utilization           = "^Utilization Data$",
    reduction_hac             = "Hospital[-]Acquired Condition \\(HAC\\) Reduction Program",
    reduction_hrr             = "Hospital Readmissions Reduction Program",
    snf_vbp_performance       = "^FY 2025 SNF VBP Aggregate Performance$",
    snf_vbp_facility          = "^FY 2025 SNF VBP Facility[-]Level Dataset$",
    snf_quality_nation        = "^Skilled Nursing Facility Quality Reporting Program [-] National Data$",
    snf_quality_provider      = "^Skilled Nursing Facility Quality Reporting Program [-] Provider Data$",
    snf_quality_swing         = "^Skilled Nursing Facility Quality Reporting Program [-] Swing Beds [-] Provider Data$",
    supplier_directory        = "^Medical Equipment Suppliers$",
    timely_hospital           = "^Timely and Effective Care [-] Hospital",
    timely_national           = "^Timely and Effective Care [-] National",
    timely_state              = "^Timely and Effective Care [-] State",
    unplan_hospital           = "^Unplanned Hospital Visits [-] Hospital",
    unplan_national           = "^Unplanned Hospital Visits [-] National",
    unplan_state              = "^Unplanned Hospital Visits [-] State",
    va_behavioral             = "^Veterans Health Administration Behavioral Health Data",
    va_provider               = "^Veterans Health Administration Provider Level Data",
    va_timely                 = "^Veterans Health Administration Timely and Effective Care Data",
    cli_abort(c("x"           = "No matches found for {.val {x}}."), call = call)
  )

  if (!exists("catalog")) .catalog <- catalogs()

  res <- select_alias(.catalog$pro$end, x)

  if (empty(res))     cli_abort(c("x" = "No matches found for {.val {x}}."), call = call)
  if (nrow(res) > 1L) cli_abort(c("x" = "> 1 match found for {.val {x}}."), call = call)

  c(res)

}
