#' @autoglobal
#' @noRd
care_list <- list(
  endpoint = list(
    contact              = "Public Reporting of Missing Digital Contact Information",
    crosswalk            = "Medicare Provider and Supplier Taxonomy Crosswalk",
    CARE_dialysis        = "Medicare Dialysis Facilities",
    enrollees            = "Public Provider Enrollment",
    facilities           = "Provider of Services File - Hospital & Non-Hospital Facilities",
    IQIES                = "Provider of Services File - Internet Quality Improvement and Evaluation System - Home Health Agency, Ambulatory Surgical Center, and Hospice Providers",
    laboratories         = "Provider of Services File - Clinical Laboratories",
    long_term            = "Long-Term Care Facility Characteristics",
    opt_out              = "Opt Out Affidavits",
    order_refer          = "Order and Referring",
    RBCS                 = "Restructured BETOS Classification System",
    transparency         = "Hospital Price Transparency Enforcement Activities and Outcomes",
    HHA_owners           = "^Home Health Agency All Owners$",
    HHA_cost_report      = "^Home Health Agency Cost Report$",
    HHA_enrollments      = "^Home Health Agency Enrollments$",
    hospice_owners       = "^Hospice All Owners$",
    hospice_enrollments  = "^Hospice Enrollments$",
    hospice_acute        = "Medicare Post-Acute Care and Hospice - by Geography & Provider",
    hospital_owners      = "^Hospital All Owners$",
    hospital_chow        = "^Hospital Change of Ownership$",
    hospital_chow_owner  = "^Hospital Change of Ownership - Owner Information$",
    hospital_enrollments = "^Hospital Enrollments$",
    RHC_owners           = "^Rural Health Clinic All Owners$",
    RHC_enrollments      = "^Rural Health Clinic Enrollments$",
    FQHC_owners          = "^Federally Qualified Health Center All Owners$",
    FQHC_enrollments     = "^Federally Qualified Health Center Enrollments$",
    PILAT_non_physicians = "^Pending Initial Logging and Tracking Non Physicians$",
    PILAT_physicians     = "^Pending Initial Logging and Tracking Physicians$",
    REVAL_group          = "^Revalidation Clinic Group Practice Reassignment$",
    REVAL_due_date       = "^Revalidation Due Date List$",
    REVAL_reassignment   = "^Revalidation Reassignment List$",
    SNF_owners           = "^Skilled Nursing Facility All Owners$",
    SNF_chow             = "^Skilled Nursing Facility Change of Ownership$",
    SNF_chow_owner       = "^Skilled Nursing Facility Change of Ownership - Owner Information$",
    SNF_cost_report      = "^Skilled Nursing Facility Cost Report$",
    SNF_enrollments      = "^Skilled Nursing Facility Enrollments$"
  ),
  temporal = list(
    quality_payment            = "^Quality Payment Program Experience$",
    IN_geography_and_service   = "^Medicare Inpatient Hospitals - by Geography and Service$",
    IN_provider                = "^Medicare Inpatient Hospitals - by Provider$",
    IN_provider_and_service    = "^Medicare Inpatient Hospitals - by Provider and Service$",
    OUT_geography_and_service  = "^Medicare Outpatient Hospitals - by Geography and Service$",
    OUT_provider_and_service   = "^Medicare Outpatient Hospitals - by Provider and Service$",
    PRX_geography_and_drug     = "^Medicare Part D Prescribers - by Geography and Drug$",
    PRX_provider               = "^Medicare Part D Prescribers - by Provider$",
    PRX_provider_and_drug      = "^Medicare Part D Prescribers - by Provider and Drug$",
    DME_geography_and_service  = "^Medicare Durable Medical Equipment, Devices & Supplies - by Geography and Service$",
    DME_provider               = "^Medicare Durable Medical Equipment, Devices & Supplies - by Referring Provider$",
    DME_provider_and_service   = "^Medicare Durable Medical Equipment, Devices & Supplies - by Referring Provider and Service$",
    DME_supplier               = "^Medicare Durable Medical Equipment, Devices & Supplies - by Supplier$",
    DME_supplier_and_service   = "^Medicare Durable Medical Equipment, Devices & Supplies - by Supplier and Service$",
    STAFF_non_nurse            = "^Payroll Based Journal Daily Non-Nurse Staffing$",
    STAFF_nurse                = "^Payroll Based Journal Daily Nurse Staffing$",
    STAFF_employee             = "^Payroll Based Journal Employee Detail Nursing Home Staffing$",
    UTIL_geography_and_service = "^Medicare Physician & Other Practitioners - by Geography and Service$",
    UTIL_provider              = "^Medicare Physician & Other Practitioners - by Provider$",
    UTIL_provider_and_service  = "^Medicare Physician & Other Practitioners - by Provider and Service$"
  )
)

#' @autoglobal
#' @noRd
caid_list <- list(
  endpoint = list(
    ACA_FUL             = "ACA Federal Upper Limits",
    MLR_summary         = "MLR Summary Reports",
    MLTSS_enroll        = "Managed Long Term Services and Supports \\(MLTSS\\) Enrollees",
    MCD_enterprise      = "Medicaid Enterprise System Datatable",
    DSH_payments        = "Disproportionate Share Hospital \\(DSH\\) Payments - Annual Reporting Requirements",
    DPR_index           = "Division of Pharmacy Releases Index dataset",
    MDRP_new            = "Product Data for Newly Reported Drugs in the Medicaid Drug Rebate Program",
    CAHPS_NAM           = "NAM CAHPS 2014 Public Use",
    enroll_mon_test     = "Monthly Enrollment - Test",
    enroll_new_adult    = "Medicaid Enrollment - New Adult Group",
    pi_data             = "PI dataset",
    tiles               = "category_tiles",

    NADAC               = "^NADAC$",
    NADAC_first         = "^First Time NADAC Rates$",
    NADAC_compare       = "^NADAC Comparison$",

    DEMO_well           = "^Medicaid and CHIP enrollees who received a well",
    DEMO_sud            = "^Medicaid and CHIP enrollees who received mental health or SUD services$",
    DEMO_disability     = "^Medicaid enrollees who qualify for benefits based on disability$",
    DEMO_premature      = "^Prematurity and severe maternal morbidity among Medicaid",
    DEMO_language       = "^Primary language spoken by the Medicaid and CHIP population$",
    DEMO_race           = "^Race and ethnicity of the national Medicaid and CHIP population$",
    DEMO_rural          = "^Rural Medicaid and CHIP enrollees$",
    DEMO_waive          = "^Section 1915",

    SERV_acute          = "^Acute Care Services Provided to the Medicaid and CHIP Population$",
    SERV_behavior       = "^Behavioral Health ServicesProvided to the Medicaid and CHIP Population$",
    SERV_perinatal      = "^Perinatal Care Services Provided to Medicaid and CHIP Beneficiaries ages 15 to 44",
    SERV_screen         = "^Health Screenings Provided to Medicaid and CHIP Beneficiaries Under Age 19",
    SERV_contra         = "^Contraceptive Care Services Provided to Medicaid and CHIP Beneficiaries ages 15 to 44",
    SERV_dental         = "^Dental Services Provided to Medicaid and CHIP Beneficiaries Under Age 19",
    SERV_pregnancy      = "^Pregnancy Outcomes for Medicaid and CHIP Beneficiaries ages 15 to 44",
    SERV_telehealth     = "^Telehealth Services Provided to the Medicaid and CHIP Population",
    SERV_vaccination    = "^Vaccinations Provided to the Medicaid and CHIP Population under age 19",
    SERV_lead           = "^Blood Lead Screening Services Provided to Medicaid and CHIP Beneficiaries",
    SERV_respiratory    = "^Respiratory Conditions in the Medicaid and CHIP Population",

    BENE_behavior       = "Beneficiaries receiving a behavioral health service by behavioral health condition, 2017-2021",
    BENE_physical       = "Beneficiaries receiving a physical health service among beneficiaries receiving a SUD service by physical health cond, 2017-2021",
    BENE_mental         = "Beneficiaries receiving a physical hlth serv among beneficiaries receiving a mental hlth serv, by physical hlth cond, 2017-2021",
    BENE_integrated     = "Beneficiaries who could benefit from integrated care, 2017-2021",
    BENE_nas            = "Number and rate of NAS per 1,000 births in newborns whose deliveries were covered by Medicaid or CHIP, 2017 - 2021",
    BENE_smm            = "Number and rate of SMM among Medicaid- and CHIP-covered deliveries, 2017 - 2021",
    BENE_postpart       = "Number of pregnant and postpartum Medicaid and CHIP beneficiaries, 2017-2021",
    BENE_delivery       = "Rate of NAS per 1,000 births in newborns whose deliveries were covered by Medicaid or CHIP, 2017 - 2019",

    PKG_month           = "Benefit Package for Medicaid and CHIP Beneficiaries by Month",
    PKG_year            = "Benefit Package for Medicaid and CHIP Beneficiaries by Year",

    DRUG_amp_mon        = "Drug AMP Reporting - Monthly",
    DRUG_amp_qtr        = "Drug AMP Reporting - Quarterly",
    DRUG_products       = "Drug Products in the Medicaid Drug Rebate Program",
    DRUG_clot           = "^Clotting Factor Drug Report",
    DRUG_pediatric      = "Exclusive Pediatric Drugs",
    DRUG_contact_manu   = "Drug Manufacturer Contacts",
    DRUG_contact_state  = "Medicaid Drug Rebate Program State Contact Information",

    DUAL_month          = "Dual Status Information for Medicaid and CHIP Beneficiaries by Month",
    DUAL_year           = "Dual Status Information for Medicaid and CHIP Beneficiaries by Year",

    MEG_month           = "Major Eligibility Group Information for Medicaid and CHIP Beneficiaries by Month",
    MEG_year            = "Major Eligibility Group Information for Medicaid and CHIP Beneficiaries by Year",

    CMS64_CAA           = "Medicaid CMS-64 CAA 2023 Increased FMAP Expenditure Data Collected through MBES/CBES",
    CMS64_FFCRA         = "Medicaid CMS-64 FFCRA Increased FMAP Expenditure",
    CMS64_adult         = "Medicaid CMS-64 New Adult Group Expenditures",

    MC_summary          = "Managed Care Enrollment Summary",
    MC_program_state    = "^Managed Care Programs\\sby\\sState$",
    MC_program_plan     = "Managed Care Enrollment by Program and Plan",
    MC_program_pop_all  = "Managed Care Enrollment by Program and Population \\(All\\)",
    MC_program_pop_dual = "Managed Care Enrollment by Program and Population \\(Duals\\)",
    MC_feat_pop         = "Managed Care Features By Enrollment Population",
    MC_feat_qa          = "Managed Care Features by QA and Performance Incentive",
    MC_bene_month       = "Managed Care Information for Medicaid and CHIP Beneficiaries by Month",
    MC_bene_year        = "Managed Care Information for Medicaid and CHIP Beneficiaries by Year",
    MC_share            = "Share of Medicaid Enrollees in Managed Care",

    FIN_mgmt            = "Medicaid Financial Management Data$",
    FIN_nation          = "Medicaid Financial Management Data  National Totals",

    Unwind_marketplace     = "HealthCare\\.gov Marketplace Medicaid Unwinding Report",
    Unwind_transition      = "HealthCare\\.gov Transitions Marketplace Medicaid Unwinding Report",
    Unwind_historic        = "Separate CHIP Enrollment by Month and State\\s.+\\sHistoric CAA/Unwinding Period",
    Unwind_SBM             = "State-based Marketplace \\(SBM\\) Medicaid Unwinding Report",

    CHIP_bene_month        = "Program Information for Medicaid and CHIP Beneficiaries by Month",
    CHIP_bene_year         = "Program Information for Medicaid and CHIP Beneficiaries by Year",
    CHIP_application       = "^CHIP Applications, Eligibility Determinations, and Enrollment Data",
    CHIP_continue          = "^Continuous Eligibility for Medicaid and CHIP Coverage$",
    CHIP_express           = "Express Lane Eligibility for Medicaid and CHIP Coverage",
    CHIP_metrics           = "Medicaid and CHIP CAA Reporting Metrics",
    CHIP_levels            = "Medicaid and CHIP Eligibility Levels",
    CHIP_renewal           = "Medicaid and CHIP Updated Renewal Outcomes",
    CHIP_presume           = "Presumptive Eligibility for Medicaid and CHIP Coverage",
    CHIP_separate          = "Separate CHIP Enrollment by Month and State",
    CHIP_application_state = "State Medicaid and CHIP Applications, Eligibility Determinations, and Enrollment Data",
    CHIP_processing_state  = "State Medicaid and CHIP Eligibility Processing Data",
    CHIP_test              = "State Medicaid and CHIP Test"
  ),
  temporal = list(
    NADAC  = "NADAC",
    MCP    = "^Managed Care Programs",
    rebate = "^Product Data for Newly Reported Drugs in the Medicaid Drug Rebate Program",
    blood  = "^Pricing Comparison for Blood Disorder Treatments",
    drug   = "^State Drug Utilization Data",
    HCQ    = "Child and Adult Health Care Quality Measures"
  )
)

#' @autoglobal
#' @noRd
open_list <- list(
  endpoint = list(
    PROF_covered      = "^Covered Recipient Profile Supplement$",
    PROF_physician    = "^Physician \\(Distinct\\) Profile Information$",
    PROF_information  = "^Profile Information$",
    PROF_mapping      = "^Provider Profile ID Mapping Table$",
    PROF_entity       = "^Reporting Entity Profile Information$",
    PROF_teaching     = "^Teaching Hospital Profile Information$",
    SUMM_dashboard    = "^Summary Dashboard",
    SUMM_state_all    = "^State Level Payment Total and Averages for all Years$",
    SUMM_state_group  = "^State Payment Totals and Averages Grouped by Nature of Payment for all Years$",
    SUMM_nation_all   = "^National Level Payment Total and Averages for all Years$",
    SUMM_nation_group = "^National Level Payment Total and Averages by Provider Specialty for all Years$"
  ),
  temporal = list(
    DATA_general        = "^General Payment Data$",
    DATA_ownership      = "^Ownership Payment Data$",
    DATA_research       = "^Research Payment Data$",
    GROUP_recip_nature  = "^Payments Grouped by Covered Recipient and Nature of Payments$",
    GROUP_recip_entity  = "^Payments Grouped by Covered Recipient and Reporting Entities$",
    GROUP_entity_nature = "^Payments Grouped by Covered Recipient and Nature of Payments$",
    GROUP_all           = "^Payments Grouped by Reporting Entities, Covered Recipient, and Nature of Payments$"
  )
)

#' @autoglobal
#' @noRd
pro_list <- list(
  endpoint = list(
    PSI90_6digit            = "CMS Medicare PSI-90 and component measures - six-digit estimate dataset",
    joint_replace           = "Comprehensive Care For Joint Replacement Model - Provider Data",
    footnote_xwalk          = "Footnote Crosswalk",
    suppliers               = "^Medical Equipment Suppliers$",
    Data_Updates            = "Data Updates",
    Measure_Dates           = "Measure Dates",
    Hospital_Maternal       = "Maternal Health - Hospital",
    Hospital_Outcomes       = "Patient-Reported Outcomes - Hospital",
    Hospital_General        = "Hospital General Information",
    Hospital_PI             = "Promoting Interoperability - Hospital",
    REDUCT_HAC              = "Hospital-Acquired Condition \\(HAC\\) Reduction Program",
    REDUCT_HRR              = "Hospital Readmissions Reduction Program",
    VOC_national            = "Value of care - National",
    VOC_PMT_nation          = "Payment - National",
    VOC_state               = "Payment - State",
    VOC_hospital            = "Payment and value of care - Hospital",
    TBL_drg_net             = "Table 1: FY2021 Net Change in Base Operating DRG Payment Amount",
    TBL_drg_dist            = "Table 2: FY2021 Distribution of Net Change in Base Operating DRG Payment Amount",
    TBL_pmt_pct             = "Table 3: FY2021 Percent Change in Medicare Payments",
    TBL_pmt_vbi             = "Table 4: FY2021 Value-Based Incentive Payment Amount",
    PDC_affiliations        = "^Facility Affiliation Data$",
    PDC_clinicians          = "^National Downloadable File$",
    PDC_utilization         = "^Utilization Data$",
    MIPS_performance        = "^PY 2022 Clinician Public Reporting: Overall MIPS Performance$",
    MIPS_patient            = "^PY 2022 Group Public Reporting: Patient Experience$",
    MIPS_clinician          = "^PY 2022 Clinician Public Reporting: MIPS Measures and Attestations$",
    MIPS_group              = "^PY 2022 Group Public Reporting: MIPS Measures and Attestations$",
    MIPS_virtual            = "^PY 2022 Virtual Group Public Reporting: MIPS Measures and Attestations$",
    LTCH_general            = "^Long-Term Care Hospital - General Information$",
    LTCH_provider           = "^Long-Term Care Hospital - Provider Data$",
    LTCH_national           = "^Long-Term Care Hospital - National Data$",
    IRF_conditions          = "^Inpatient Rehabilitation Facility - Conditions$",
    IRF_general             = "^Inpatient Rehabilitation Facility - General Information$",
    IRF_provider            = "^Inpatient Rehabilitation Facility - Provider Data$",
    IRF_national            = "^Inpatient Rehabilitation Facility - National Data$",
    SPICE_general           = "^Hospice - General Information$",
    SPICE_provider          = "^Hospice - Provider Data$",
    SPICE_state             = "^Hospice - State Data$",
    SPICE_zip               = "^Hospice - Zip Data$",
    SPICE_national          = "^Hospice-National Data$",
    HHVBP_agency            = "^Expanded Home Health Value-Based Purchasing \\(HHVBP\\) Model - Agency Data$",
    HHVBP_cohort            = "^Expanded Home Health Value-Based Purchasing \\(HHVBP\\) Model - Cohort Data$",
    HHC_range               = "^Home Health Care - Measure Date Range$",
    HHC_national            = "^Home Health Care - National Data$",
    HHC_state               = "^Home Health Care - State by State Data$",
    HHC_zip                 = "^Home Health Care - Zip Codes$",
    HHC_agency              = "^Home Health Care Agencies$",
    SNF_VBP_agg             = "^FY 2025 SNF VBP Aggregate Performance$",
    SNF_VBP_fac             = "^FY 2025 SNF VBP Facility-Level Dataset$",
    SNF_quality_nation      = "^Skilled Nursing Facility Quality Reporting Program - National Data$",
    SNF_quality_provider    = "^Skilled Nursing Facility Quality Reporting Program - Provider Data$",
    SNF_quality_swing       = "^Skilled Nursing Facility Quality Reporting Program - Swing Beds - Provider Data$",
    NH_ownership            = "^Ownership$",
    NH_penalties            = "^Penalties$",
    NH_provider             = "^Provider Information$",
    NH_citation             = "^Citation Code Look-up$",
    NH_fire                 = "^Fire Safety Deficiencies$",
    NH_deficiencies         = "^Health Deficiencies$",
    NH_inspection           = "^Inspection Dates$",
    NH_quality_mds          = "^MDS Quality Measures$",
    NH_quality_claims       = "^Medicare Claims Quality Measures$",
    NH_state_avg            = "^State US Averages$",
    NH_state_cut            = "^State-Level Health Inspection Cut Points$",
    NH_interval             = "^Nursing Home Data Collection Interval",
    DIAL_facility           = "^Dialysis Facility - Listing by Facility$",
    DIAL_national           = "^Dialysis Facility - National Averages$",
    DIAL_state              = "^Dialysis Facility - State Averages$",
    ESRD_depression         = "^ESRD QIP - Clinical Depression Screening and Follow-up",
    ESRD_complete           = "^ESRD QIP - Complete QIP Data",
    ESRD_adequacy           = "^ESRD QIP - Dialysis Adequacy",
    ESRD_footnotes          = "^ESRD QIP - Footnotes",
    ESRD_hypercalcemia      = "^ESRD QIP - Hypercalcemia",
    ESRD_medication         = "^ESRD QIP - Medication Reconciliation",
    ESRD_infection          = "^ESRD QIP - NHSN Bloodstream Infection",
    ESRD_event              = "^ESRD QIP - NHSN Dialysis Event Measure",
    ESRD_waitlist           = "^ESRD QIP - Percentage of Prevalent Patients Waitlisted",
    ESRD_hospitalization    = "^ESRD QIP - Standardized Hospitalization Ratio",
    ESRD_readmission        = "^ESRD QIP - Standardized Readmission Ratio",
    ESRD_transfusion        = "^ESRD QIP - Standardized Transfusion Ratio",
    ESRD_performance        = "^ESRD QIP - Total Performance Scores",
    ESRD_ultrafiltration    = "^ESRD QIP - Ultrafiltration Rate",
    ESRD_vascular           = "^ESRD QIP - Vascular Access Topic",
    CAHPS_SPICE_nation      = "^Hospice care - National CAHPS Hospice Survey Data$",
    CAHPS_SPICE_provider    = "^Hospice care - Provider CAHPS Hospice Survey Data$",
    CAHPS_SPICE_state       = "^Hospice care - State CAHPS Hospice Survey Data$",
    CAHPS_HHC_patient       = "^Home Health Care - Patient Survey \\(HHCAHPS\\) 2023Q4 to 2024Q3$",
    CAHPS_HHC_measure       = "^Home Health Care - Patient Survey \\(HHCAHPS\\) Measure Dates 2023Q4 to 2024Q3$",
    CAHPS_HHC_national      = "^Home Health Care - Patient Survey \\(HHCAHPS\\) National Data 2023Q4 to 2024Q3$",
    CAHPS_HHC_state         = "^Home Health Care - Patient Survey \\(HHCAHPS\\) State Data 2023Q4 to 2024Q3$",
    CAHPS_ICH_esrd          = "^ESRD QIP - In-Center Hemodialysis Consumer Assessment Of Healthcare Providers And Services Systems \\(ICH CAHPS\\) Survey",
    CAHPS_ICH_facility      = "^Patient survey \\(ICH CAHPS\\) - Facility$",
    CAHPS_ICH_national      = "^Patient survey \\(ICH CAHPS\\) - National$",
    CAHPS_ICH_state         = "^Patient survey \\(ICH CAHPS\\) - State$",
    ASC_facility            = "Ambulatory Surgical Center Quality Measures - Facility",
    ASC_national            = "Ambulatory Surgical Center Quality Measures - National",
    ASC_state               = "Ambulatory Surgical Center Quality Measures - State",
    COMP_hospital           = "Complications and Deaths - Hospital",
    COMP_national           = "Complications and Deaths - National",
    COMP_state              = "Complications and Deaths - State",
    PCH_COMP_hospital       = "Complications and Unplanned Hospital Visits - PPS-Exempt Cancer Hospital - Hospital",
    PCH_COMP_national       = "Complications and Unplanned Hospital Visits - PPS-Exempt Cancer Hospital - National",
    EQUI_hospital           = "Health Equity - Hospital",
    EQUI_national           = "Health Equity - National",
    EQUI_state              = "Health Equity - State",
    HAI_hospital            = "Healthcare Associated Infections - Hospital",
    HAI_national            = "Healthcare Associated Infections - National",
    HAI_state               = "Healthcare Associated Infections - State",
    HAI_PCH                 = "Safety and Healthcare-Associated Infection Measures - PPS-Exempt Cancer Hospital",
    HVBP_outcomes           = "Hospital Value-Based Purchasing \\(HVBP\\) - Clinical Outcomes Domain Scores",
    HVBP_efficiency         = "Hospital Value-Based Purchasing \\(HVBP\\) - Efficiency Scores",
    HVBP_engagement         = "Hospital Value-Based Purchasing \\(HVBP\\) - Person and Community Engagement Domain Scores \\(HCAHPS\\)",
    HVBP_safety             = "Hospital Value-Based Purchasing \\(HVBP\\) - Safety",
    HVBP_performance        = "Hospital Value-Based Purchasing \\(HVBP\\) - Total Performance Score",
    IPF_national            = "Inpatient Psychiatric Facility Quality Measure Data - National",
    IPF_facility            = "Inpatient Psychiatric Facility Quality Measure Data - by Facility",
    IPF_state               = "Inpatient Psychiatric Facility Quality Measure Data - by State",
    MSPB_claim              = "Medicare Hospital Spending by Claim",
    MSPB_hospital           = "Medicare Spending Per Beneficiary - Hospital$",
    MSPB_decimal            = "Medicare Spending Per Beneficiary - Hospital Additional Decimal Places$",
    MSPB_national           = "Medicare Spending Per Beneficiary - National",
    MSPB_state              = "Medicare Spending Per Beneficiary - State",
    OUT_img_hospital        = "Outpatient Imaging Efficiency - Hospital",
    OUT_img_national        = "Outpatient Imaging Efficiency - National",
    OUT_img_state           = "Outpatient Imaging Efficiency - State",
    CAHPS_OAS_footnotes     = "Outpatient and Ambulatory Surgery Consumer Assessment of Healthcare Providers and Systems \\(OAS CAHPS\\) survey - Footnotes",
    CAHPS_OAS_ASC_facility  = "Outpatient and Ambulatory Surgery Consumer Assessment of Healthcare Providers and Systems \\(OAS CAHPS\\) survey for ambulatory surgical centers - Facility",
    CAHPS_OAS_ASC_national  = "Outpatient and Ambulatory Surgery Consumer Assessment of Healthcare Providers and Systems \\(OAS CAHPS\\) survey for ambulatory surgical centers - National",
    CAHPS_OAS_ASC_state     = "Outpatient and Ambulatory Surgery Consumer Assessment of Healthcare Providers and Systems \\(OAS CAHPS\\) survey for ambulatory surgical centers - State",
    CAHPS_OAS_HOSP_facility = "Outpatient and Ambulatory Surgery Consumer Assessment of Healthcare Providers and Systems \\(OAS CAHPS\\) survey for hospital outpatient departments - Facility",
    CAHPS_OAS_HOSP_national = "Outpatient and Ambulatory Surgery Consumer Assessment of Healthcare Providers and Systems \\(OAS CAHPS\\) survey for hospital outpatient departments - National",
    CAHPS_OAS_HOSP_state    = "Outpatient and Ambulatory Surgery Consumer Assessment of Healthcare Providers and Systems \\(OAS CAHPS\\) survey for hospital outpatient departments - State",
    PALL_hospital           = "Palliative Care - PPS-Exempt Cancer Hospital - Hospital",
    PALL_national           = "Palliative Care - PPS-Exempt Cancer Hospital - National",
    HCAHPS_PCH_hospital     = "Patient Survey \\(PCH - HCAHPS\\) PPS-Exempt Cancer Hospital - Hospital",
    HCAHPS_PCH_national     = "Patient Survey \\(PCH - HCAHPS\\) PPS-Exempt Cancer Hospital - National",
    HCAHPS_PCH_state        = "Patient Survey \\(PCH - HCAHPS\\) PPS-Exempt Cancer Hospital - State",
    HCAHPS_hospital         = "Patient survey \\(HCAHPS\\) - Hospital",
    HCAHPS_national         = "Patient survey \\(HCAHPS\\) - National",
    HCAHPS_state            = "Patient survey \\(HCAHPS\\) - State",
    Timely_hospital         = "Timely and Effective Care - Hospital",
    Timely_national         = "Timely and Effective Care - National",
    Timely_state            = "Timely and Effective Care - State",
    Unplanned_hospital      = "Unplanned Hospital Visits - Hospital",
    Unplanned_national      = "Unplanned Hospital Visits - National",
    Unplanned_state         = "Unplanned Hospital Visits - State",
    VA_behavioral           = "Veterans Health Administration Behavioral Health Data",
    VA_provider             = "Veterans Health Administration Provider Level Data",
    VA_timely               = "Veterans Health Administration Timely and Effective Care Data"
  ),
  group = list(
    ALIAS = "NAME"
  )
)

# #' @autoglobal
# #' @noRd
# example_list <- list(
#   endpoint = list(
#     ALIAS = "NAME"
#   ),
#   temporal = list(
#     ALIAS = "NAME"
#   )
# )

# temp1 <- '{names(caid_temp_list)} = "{unlist(caid_temp_list, use.names = FALSE)}", '
# temp2 <- 'switch(x, <<xx>> cli_abort(c("x" = "No matches found for {.val {x}}."), call = call))'
#
# xx <- glue(temp1) |> glue_collapse(sep = "\n")
# x  <- glue(temp2, .open = "<<", .close = ">>") |> parse_expr() |> eval_bare()
