# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  # <open_Dataset>
  ".api__openpay",
  # <provider_dataset>
  ".api__provider",
  # <public_dataset>
  # <public_temporal>
  ".api__public",
  # <load_provider>
  "@type",
  # <load_provider>
  "accessLevel",
  # <load_public>
  "accessURL",
  # <load_public>
  "accrualPeriodicity",
  # <load_provider>
  "archiveExclude",
  # <load_provider>
  "bureauCode",
  # <load_public>
  "contactPoint",
  # <load_public>
  # <load_openpayments>
  "describedBy",
  # <load_public>
  # <load_provider>
  # <load_openpayments>
  # <open_clean_temp>
  # <open_clean_grouped>
  # <open_grouped>
  "description",
  # <load_provider>
  "distribution",
  # <load_public>
  # <load_openpayments>
  # <get_resources>
  "downloadURL",
  # <get_resources>
  "ext",
  # <get_resources>
  "fileSize",
  # <load_public>
  # <load_provider>
  # <load_openpayments>
  "identifier",
  # <load_provider>
  "issued",
  # <load_public>
  # <load_provider>
  # <load_openpayments>
  "keyword",
  # <load_public>
  "landingPage",
  # <load_public>
  "mediaType",
  # <load_public>
  # <load_provider>
  # <load_openpayments>
  # <open_profiles>
  # <open_grouped>
  # <open_general>
  # <open_research>
  # <open_ownership>
  "modified",
  # <get_resources>
  "name",
  # <load_provider>
  "programCode",
  # <load_provider>
  "publisher",
  # <load_public>
  "references",
  # <load_provider>
  "released",
  # <load_public>
  "resourcesAPI",
  # <get_resources>
  "size",
  # <load_public>
  # <load_openpayments>
  "temporal",
  # <load_public>
  # <load_provider>
  # <load_openpayments>
  # <open_Dataset>
  "theme",
  # <load_public>
  # <load_openpayments>
  # <public_dataset>
  # <public_temporal>
  # <open_clean_temp>
  # <open_clean_grouped>
  # <open_profiles>
  # <open_grouped>
  # <open_Dataset>
  # <provider_dataset>
  "title",
  # <load_openpayments>
  # <open_clean_temp>
  # <open_clean_grouped>
  # <open_Dataset>
  "year",
  NULL
))
