# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  # <catalog_main>
  "accessURL",
  # <catalog_main>
  "accrualPeriodicity",
  # <catalog_main>
  # <main_temp_group>
  # <catalog_open>
  # <catalog_provider>
  "contact",
  # <catalog_main>
  "current",
  # <main_temp_group>
  "data",
  # <catalog_main>
  "describedBy",
  # <catalog_main>
  # <catalog_open>
  # <catalog_provider>
  "description",
  # <catalog_main>
  "dictionary",
  # <catalog_main>
  "distribution",
  # <TemporalMain>
  # <TemporalOpen>
  # <catalog_open>
  # <catalog_provider>
  "download",
  # <catalog_main>
  "downloadURL",
  # <TemporalMain>
  "filetype",
  # <main_temp_group>
  # <catalog_provider>
  "group",
  # <TemporalMain>
  # <TemporalOpen>
  # <catalog_main>
  # <main_temp_group>
  # <catalog_open>
  # <catalog_provider>
  "identifier",
  # <catalog_provider>
  "issued",
  # <catalog_open>
  "keyword",
  # <catalog_main>
  # <catalog_provider>
  "landingPage",
  # <perform_request_provider>
  "limit",
  # <catalog_main>
  "mediaType",
  # <TemporalMain>
  # <TemporalOpen>
  # <catalog_main>
  # <catalog_open>
  # <catalog_provider>
  "modified",
  # <catalog_main>
  # <main_temp_group>
  "periodicity",
  # <catalog_main>
  "references",
  # <catalog_provider>
  "released",
  # <TemporalMain>
  # <main_temp_group>
  "resources",
  # <catalog_main>
  "resourcesAPI",
  # <main_temp_dims>
  "rows",
  # <catalog_main>
  "site",
  # <catalog_main>
  "temporal",
  # <catalog_provider>
  "theme",
  # <TemporalMain>
  # <TemporalOpen>
  # <catalog_main>
  # <main_temp_group>
  # <catalog_open>
  # <provider_current_group>
  # <catalog_provider>
  "title",
  # <TemporalMain>
  # <TemporalOpen>
  # <catalog_main>
  # <main_temp_group>
  # <catalog_open>
  "year",
  NULL
))
