# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  # <select_caid>
  # <select_caid_temp>
  # <select_care>
  # <select_care_temp>
  # <select_hgov>
  # <select_hgov_temp>
  # <select_open>
  # <select_open_temp>
  # <select_pro>
  ".catalog",
  # <select_endpoint>
  # <select_temporal>
  ".catnew",
  # <catalog_care>
  "accessURL",
  # <catalog_care>
  # <catalog_caid>
  # <catalog_hgov>
  "accrualPeriodicity",
  # <clinicians>
  "adr_ln_1",
  # <clinicians>
  "adr_ln_2",
  # <clinicians>
  "adrs_id",
  # <quality_metrics>
  "category",
  # <catalog_care>
  # <catalog_pro>
  # <catalog_open>
  # <catalog_caid>
  # <catalog_hgov>
  # <select_hgov_temp>
  "contact",
  # <npi_nppes>
  # <.nppes_multi_npi>
  "created_epoch",
  # <select_temporal>
  # <select_caid_temp>
  # <select_care_temp>
  # <select_hgov_temp>
  # <select_open_temp>
  "data",
  # <quality_eligibility>
  "date_approved",
  # <catalog_care>
  "describedBy",
  # <catalog_care>
  # <catalog_pro>
  # <catalog_open>
  # <catalog_caid>
  # <catalog_hgov>
  # <open_dictionary>
  "description",
  # <catalog_care>
  # <catalog_pro>
  "dictionary",
  # <catalog_care>
  # <catalog_caid>
  # <catalog_hgov>
  "distribution",
  # <catalog_care>
  # <catalog_pro>
  # <catalog_open>
  "download",
  # <catalog_care>
  # <tidy_resources>
  "downloadURL",
  # <select_temporal>
  # <select_caid_temp>
  # <select_care_temp>
  # <select_hgov_temp>
  # <select_open_temp>
  "endpoints",
  # <quality_eligibility>
  "enroll_year",
  # <quality_eligibility>
  "entity",
  # <catalog_caid>
  # <catalog_hgov>
  # <tidy_resources>
  "ext",
  # <tidy_resources>
  "fileSize",
  # <catalog_care>
  "filetype",
  # <quality_eligibility>
  "first_name",
  # <quality_eligibility>
  "firstApprovedDate",
  # <clinicians>
  "grd_yr",
  # <catalog_pro>
  "group",
  # <clinicians>
  "grp_assgn",
  # <catalog_caid>
  "id",
  # <clinicians>
  "ind_assgn",
  # <quality_eligibility>
  "is_maqi",
  # <quality_eligibility>
  "is_new",
  # <catalog_pro>
  # <catalog_hgov>
  "issued",
  # <catalog_open>
  "keyword",
  # <catalog_care>
  # <catalog_pro>
  "landingPage",
  # <quality_eligibility>
  "last_name",
  # <npi_nppes>
  # <.nppes_multi_npi>
  "last_updated_epoch",
  # <clinicians>
  "ln_2_sprs",
  # <catalog_care>
  "main",
  # <catalog_care>
  "mediaType",
  # <quality_metrics>
  "metric",
  # <quality_eligibility>
  "middle_name",
  # <catalog_care>
  # <catalog_pro>
  # <catalog_open>
  # <catalog_caid>
  # <catalog_hgov>
  "modified",
  # <catalog_caid>
  # <catalog_hgov>
  "N",
  # <tidy_resources>
  # <open_dictionary>
  "name",
  # <quality_eligibility>
  "nationalProviderIdentifierType",
  # <clinicians>
  "num_org_mem",
  # <catalog_care>
  # <catalog_caid>
  # <catalog_hgov>
  "periodicity",
  # <catalog_care>
  "references",
  # <catalog_pro>
  "released",
  # <catalog_care>
  "resources",
  # <catalog_care>
  "resourcesAPI",
  # <clinicians>
  "sec_spec_1",
  # <clinicians>
  "sec_spec_2",
  # <clinicians>
  "sec_spec_3",
  # <clinicians>
  "sec_spec_4",
  # <catalog_care>
  "site",
  # <tidy_resources>
  "size",
  # <quality_eligibility>
  "specialty",
  # <quality_eligibility>
  "specialty_category",
  # <quality_eligibility>
  "specialty_description",
  # <quality_eligibility>
  "specialty_type",
  # <clinicians>
  "telehlth",
  # <catalog_care>
  "temporal",
  # <catalog_pro>
  "theme",
  # <catalog_care>
  # <catalog_pro>
  # <catalog_open>
  # <catalog_caid>
  # <catalog_hgov>
  # <select_alias>
  "title",
  # <catalog_care>
  # <catalog_open>
  # <catalog_caid>
  # <catalog_hgov>
  # <tidy_resources>
  # <open_dictionary>
  "year",
  # <quality_eligibility>
  "years_in_medicare",
  NULL
))
