#' Create Groups of Endpoints
#' @param member_names `<chr>` Alias representing the CMS data endpoint.
#' @param group_name   `<chr>` Name of the group.
#' @param quick        `<lgl>` call `quick_()` method on group if `TRUE`.
#' @param offset       `<int>` Offset for pagination.
#' @param limit        `<int>` Limit for pagination.
#' @returns S7 `class_group` object.
#' @examplesIf rlang::is_interactive()
#' new_group(c("hgov_local_help", "hgov_qhp_business"))
#' new_group(c("hgov_local_help", "hgov_qhp_business"), quick = TRUE)
#' @autoglobal
#' @export
new_group <- function(member_names,
                      group_name = NULL,
                      quick      = FALSE,
                      offset     = 0,
                      limit      = 10) {

  check_required(member_names)
  check_bool(quick)
  check_character(group_name, allow_null = TRUE)

  ob <- ifelse_(
    length(member_names) == 1,
    select_member(member_names),
    class_group(
      group   = group_name %||% paste0(member_names, collapse = " | "),
      members = set_names(map(
        member_names,
        select_member),
        member_names)
      )
    )

  if (!quick) return(ob)

  quick_(ob, offset = offset, limit = limit)
}

#' Create Collection of Endpoints
#' @param alias `<chr>` Alias representing the CMS data endpoint.
#' @param call `<env>` Environment to use for error reporting.
#' @returns S7 `class_collection` object.
#' @examplesIf rlang::is_interactive()
#' new_collection("caid_demographics")
#' new_collection("caid_unwind")
#' new_collection("caid_services") |> query_nresults()
#' @autoglobal
#' @export
new_collection <- function(alias, call = caller_env()) {

  check_required(alias)

  x <- aka$get(alias)

  if (is_empty(x)) {
    cli_abort(
      c("x" = "{.emph group alias} {.val {alias}} is invalid."),
      call = call)
  }

  class_collection(
    group = "Collection",
    set_names(map(x, caid_endpoint), x))
}

#' @autoglobal
#' @noRd
make_quick_entry <- function(x) {
  x |> names() |> cat(sep = " = ,\n")
}

#' @autoglobal
#' @noRd
select_member <- function(x, call = caller_env()) {
  switch(
    x,
    ahqr_psi11                         = ,
    aip_plan                           = ,
    cpc_primary                        = ,
    cpc_joint                          = ,
    county_risk_spend                  = ,
    hac_measures                       = ,
    esrd_group_perf                    = ,
    fiss_rendering                     = ,
    home_infusion                      = ,
    ffs_cert                           = ,
    diabetes_prevention                = ,
    clinician_group                    = ,
    lab_fee_schedule                   = ,
    aco_reach_aligned                  = ,
    aco_reach_eligible                 = ,
    aco_reach_results                  = ,
    aco_reach_providers                = ,
    aco_reach_orgs                     = ,
    aco_pioneer                        = ,
    aco_participants                   = ,
    aco_snf_affiliate                  = ,
    aco_organizations                  = ,
    aco_bene_cnty                      = ,
    care_dialysis                      = ,
    care_enrollees                     = ,
    care_facilities                    = ,
    care_pos_iqies                     = ,
    care_pos_labs                      = ,
    care_ltcf                          = ,
    care_opt_out                       = ,
    care_order_refer                   = ,
    care_restruct_betos                = ,
    care_miss_contact                  = ,
    care_taxonomy_crosswalk            = ,
    care_caid_managed_care             = ,
    care_caid_opioid_geo               = ,
    care_caid_drug_spend               = ,
    care_benes                         = ,
    cms_ma_enroll                      = ,
    cms_ma_outpatient                  = ,
    cms_ma_other                       = ,
    cms_ma_inpatient                   = ,
    cms_ma_snf                         = ,
    cms_deaths                         = ,
    cms_hha                            = ,
    cms_hospice                        = ,
    cms_inpatient                      = ,
    cms_new_enroll                     = ,
    cms_outpatient                     = ,
    cms_tos                            = ,
    cms_partd                          = ,
    cms_partd_enroll                   = ,
    cms_phys_npp_supp                  = ,
    cms_premiums                       = ,
    cms_providers                      = ,
    cms_snf                            = ,
    cms_total_enroll                   = ,
    cms_dual_enroll                    = ,
    cms_orig_enroll                    = ,
    nhome_mds_facility                 = ,
    nhome_mds_total                    = ,
    market_cbsa                        = ,
    market_state_cnty                  = ,
    partb_drug_discard                 = ,
    partb_drug_spend                   = ,
    partd_drug_spend                   = ,
    partd_opioid                       = ,
    bene_survey_covid                  = ,
    bene_survey_cost                   = ,
    bene_survey_file                   = ,
    geovar_adv                         = ,
    geovar_hrr                         = ,
    geovar_nsc                         = ,
    pdp_month                          = ,
    pdp_quarter                        = ,
    hha_owners                         = ,
    hha_costreport                     = ,
    hha_enrollments                    = ,
    hospice_owners                     = ,
    hospice_enrollments                = ,
    hospice_acute                      = ,
    hospital_transparency              = ,
    hospital_owners                    = ,
    hospital_chow                      = ,
    hospital_chow_owner                = ,
    hospital_enrollments               = ,
    hospital_costreport                = ,
    hospital_service_area              = ,
    rhc_owners                         = ,
    rhc_enrollments                    = ,
    fqhc_owners                        = ,
    fqhc_enrollments                   = ,
    pilat_non_physician                = ,
    pilat_physician                    = ,
    revalid_group                      = ,
    revalid_due                        = ,
    revalid_list                       = ,
    snf_owners                         = ,
    snf_chow                           = ,
    snf_chow_owner                     = ,
    snf_cost_report                    = ,
    snf_enrollments                    = care_endpoint(x),
    quality_payment                    = ,
    procedure_summary                  = ,
    dialysis_facility                  = ,
    aco_shared_savings                 = ,
    opioid_treatment                   = ,
    hospital_costreport                = ,
    snf_costreport                     = ,
    hha_costreport                     = ,
    nhome_performance                  = ,
    nhome_mds_frequency                = ,
    nhome_mds_facility                 = ,
    inpatient_geography                = ,
    inpatient_provider                 = ,
    inpatient_service                  = ,
    outpatient_geography               = ,
    outpatient_service                 = ,
    prx_geography                      = ,
    prx_provider                       = ,
    prx_drug                           = ,
    dme_geography                      = ,
    dme_provider                       = ,
    dme_service                        = ,
    dme_supplier                       = ,
    dme_supplier_service               = ,
    nhome_staff_nonurse                = ,
    nhome_staff_nurse                  = ,
    nhome_staff_employee               = ,
    util_geography                     = ,
    util_provider                      = ,
    util_service                       = care_temporal(x),
    asc_facility                       = ,
    asc_national                       = ,
    asc_state                          = ,
    cahps_hospice_nation               = ,
    cahps_hospice_provider             = ,
    cahps_hospice_state                = ,
    cahps_hhc_patient                  = ,
    cahps_hhc_measure                  = ,
    cahps_hhc_national                 = ,
    cahps_hhc_state                    = ,
    cahps_ich_esrd                     = ,
    cahps_ich_facility                 = ,
    cahps_ich_national                 = ,
    cahps_ich_state                    = ,
    cahps_oas_footnotes                = ,
    cahps_oas_asc_facility             = ,
    cahps_oas_asc_national             = ,
    cahps_oas_asc_state                = ,
    cahps_oas_hosp_facility            = ,
    cahps_oas_hosp_national            = ,
    cahps_oas_hosp_state               = ,
    hcahps_pch_hospital                = ,
    hcahps_pch_national                = ,
    hcahps_pch_state                   = ,
    hcahps_hospital                    = ,
    hcahps_national                    = ,
    hcahps_state                       = ,
    complication_hospital              = ,
    complication_national              = ,
    complication_state                 = ,
    complication_pch_hospital          = ,
    complication_pch_national          = ,
    dialysis_byfacility                = ,
    dialysis_national                  = ,
    dialysis_state                     = ,
    esrd_depression                    = ,
    esrd_complete                      = ,
    esrd_adequacy                      = ,
    esrd_footnotes                     = ,
    esrd_hypercalcemia                 = ,
    esrd_medication                    = ,
    esrd_infection                     = ,
    esrd_event                         = ,
    esrd_waitlist                      = ,
    esrd_hospitalization               = ,
    esrd_readmission                   = ,
    esrd_transfusion                   = ,
    esrd_performance                   = ,
    esrd_ultrafiltration               = ,
    esrd_vascular                      = ,
    hai_hospital                       = ,
    hai_national                       = ,
    hai_state                          = ,
    hai_pch                            = ,
    he_hospital                        = ,
    he_national                        = ,
    he_state                           = ,
    hhc_range                          = ,
    hhc_national                       = ,
    hhc_state                          = ,
    hhc_zip                            = ,
    hhc_agency                         = ,
    hhvbp_agency                       = ,
    hhvbp_cohort                       = ,
    hvbp_outcomes                      = ,
    hvbp_efficiency                    = ,
    hvbp_engagement                    = ,
    hvbp_safety                        = ,
    hvbp_performance                   = ,
    hospice_general                    = ,
    hospice_provider                   = ,
    hospice_state                      = ,
    hospice_zip                        = ,
    hospice_national                   = ,
    hospital_psi90                     = ,
    hospital_joint                     = ,
    hospital_footnote                  = ,
    hospital_update                    = ,
    hospital_dates                     = ,
    hospital_maternal                  = ,
    hospital_outcomes                  = ,
    hospital_general                   = ,
    hospital_pi                        = ,
    hospital_voc_nation                = ,
    hospital_voc_hosp                  = ,
    hospital_pmt_state                 = ,
    hospital_pmt_nation                = ,
    hospital_drg_net                   = ,
    hospital_drg_dist                  = ,
    hospital_pmt_pct                   = ,
    hospital_pmt_vbi                   = ,
    ipf_national                       = ,
    ipf_facility                       = ,
    ipf_state                          = ,
    irf_conditions                     = ,
    irf_general                        = ,
    irf_provider                       = ,
    irf_national                       = ,
    ltch_general                       = ,
    ltch_provider                      = ,
    ltch_national                      = ,
    mips_performance                   = ,
    mips_patient                       = ,
    mips_clinician                     = ,
    mips_group                         = ,
    mips_virtual                       = ,
    mspb_claim                         = ,
    mspb_hospital                      = ,
    mspb_decimal                       = ,
    mspb_national                      = ,
    mspb_state                         = ,
    nursing_ownership                  = ,
    nursing_penalties                  = ,
    nursing_provider                   = ,
    nursing_citation                   = ,
    nursing_fire                       = ,
    nursing_deficiencies               = ,
    nursing_inspection                 = ,
    nursing_quality_mds                = ,
    nursing_quality_claims             = ,
    nursing_state_avg                  = ,
    nursing_state_cut                  = ,
    nursing_interval                   = ,
    out_img_hospital                   = ,
    out_img_national                   = ,
    out_img_state                      = ,
    pch_pall_hospital                  = ,
    pch_pall_national                  = ,
    pdc_affiliations                   = ,
    pdc_clinicians                     = ,
    pdc_utilization                    = ,
    reduction_hac                      = ,
    reduction_hrr                      = ,
    snf_vbp_performance                = ,
    snf_vbp_facility                   = ,
    snf_quality_nation                 = ,
    snf_quality_provider               = ,
    snf_quality_swing                  = ,
    supplier_directory                 = ,
    timely_hospital                    = ,
    timely_national                    = ,
    timely_state                       = ,
    unplan_hospital                    = ,
    unplan_national                    = ,
    unplan_state                       = ,
    va_behavioral                      = ,
    va_provider                        = ,
    va_timely                          = prov_endpoint(x),
    profile_covered                    = ,
    profile_physician                  = ,
    profile_information                = ,
    profile_mapping                    = ,
    profile_entity                     = ,
    profile_teaching                   = ,
    summary_dashboard                  = ,
    summary_state                      = ,
    summary_nature                     = ,
    summary_national                   = ,
    summary_specialty                  = open_endpoint(x),
    payment_general                    = ,
    payment_ownership                  = ,
    payment_research                   = ,
    grouped_covered_nature             = ,
    grouped_covered_entity             = ,
    grouped_entity_nature              = ,
    grouped_entity_covered_nature      = ,
    grouped_state_nature               = open_temporal(x),
    aca_ful                            = ,
    caid_drug_rebate                   = ,
    caid_enroll_month                  = ,
    caid_enroll_adult                  = ,
    caid_enterprise                    = ,
    caid_pi                            = ,
    caid_tiles                         = ,
    mlr_summary                        = ,
    managed_longterm                   = ,
    dsh_requirement                    = ,
    pharm_release_index                = ,
    cahps_nam_puf                      = ,
    caid_nadac                         = ,
    caid_nadac_first                   = ,
    caid_nadac_compare                 = ,
    caid_finance_mgmt                  = ,
    caid_finance_nation                = ,
    caid_chip_bene_month               = ,
    caid_chip_bene_year                = ,
    caid_chip_application              = ,
    caid_chip_continue                 = ,
    caid_chip_express                  = ,
    caid_chip_metrics                  = ,
    caid_chip_levels                   = ,
    caid_chip_renewal                  = ,
    caid_chip_presume                  = ,
    caid_chip_separate                 = ,
    caid_chip_application_state        = ,
    caid_chip_processing_state         = ,
    caid_chip_test                     = ,
    demo_wellvisit                     = ,
    demo_mental                        = ,
    demo_disability                    = ,
    demo_prematurity                   = ,
    demo_language                      = ,
    demo_ethnicity                     = ,
    demo_rural                         = ,
    demo_waiver                        = ,
    service_acute                      = ,
    service_behavior                   = ,
    service_perinatal                  = ,
    service_screening                  = ,
    service_contraceptive              = ,
    service_dental                     = ,
    service_pregnancy                  = ,
    service_telehealth                 = ,
    service_vaccination                = ,
    service_bloodlead                  = ,
    service_respiratory                = ,
    benes_behavior                     = ,
    benes_physical                     = ,
    benes_mental                       = ,
    benes_integrated                   = ,
    benes_nas                          = ,
    benes_smm                          = ,
    benes_pregnant                     = ,
    benes_delivery                     = ,
    benefit_pkg_month                  = ,
    benefit_pkg_year                   = ,
    drug_amp_month                     = ,
    drug_amp_quarter                   = ,
    drug_products                      = ,
    drug_clot                          = ,
    drug_pediatric                     = ,
    drug_contact_manu                  = ,
    drug_contact_state                 = ,
    dual_status_month                  = ,
    dual_status_year                   = ,
    meg_month                          = ,
    meg_year                           = ,
    cms64_caa                          = ,
    cms64_ffcra                        = ,
    cms64_adult                        = ,
    managed_care_summary               = ,
    managed_care_program_state         = ,
    managed_care_program_plan          = ,
    managed_care_program_pop_all       = ,
    managed_care_program_pop_dual      = ,
    managed_care_feat_pop              = ,
    managed_care_feat_qa               = ,
    managed_care_bene_month            = ,
    managed_care_bene_year             = ,
    managed_care_share                 = ,
    unwind_marketplace                 = ,
    unwind_transition                  = ,
    unwind_historic                    = ,
    unwind_sbm                         = caid_endpoint(x),
    nadac_year                         = ,
    managed_care_state                 = ,
    caid_drug_rebate_week              = ,
    blood_disorder                     = ,
    state_drug_util                    = ,
    healthcare_quality                 = caid_temporal(x),
    hgov_auto_pop                      = ,
    hgov_ab_reg_comp                   = ,
    hgov_ab_sus_term                   = ,
    hgov_ab_reg_gloss                  = ,
    hgov_ab_reg_trac                   = ,
    hgov_catastrophic                  = ,
    hgov_contact_admin                 = ,
    hgov_counties                      = ,
    hgov_county_service                = ,
    hgov_partner_lookup                = ,
    hgov_partner_reference             = ,
    hgov_partner_directory             = ,
    hgov_partner_enrollment            = ,
    hgov_nipr_authority                = ,
    hgov_nipr_state                    = ,
    hgov_response_codes                = ,
    hgov_rolling_draft                 = ,
    hgov_slcsp_county                  = ,
    hgov_states                        = ,
    hgov_local_help                    = ,
    hgov_qhp_consumer                  = ,
    hgov_qhp_aptc                      = ,
    hgov_qhp_csr                       = ,
    hgov_qhp_metal                     = ,
    hgov_qhp_income                    = ,
    hgov_qhp_ethnicity                 = ,
    hgov_qhp_age                       = ,
    hgov_qhp_business                  = hgov_endpoint(x),
    hgov_mlr_datasets                  = ,
    hgov_puf_benefits                  = ,
    hgov_puf_business                  = ,
    hgov_puf_machine                   = ,
    hgov_puf_network                   = ,
    hgov_puf_plan_attr                 = ,
    hgov_puf_plan_walk                 = ,
    hgov_puf_rate                      = ,
    hgov_puf_service                   = ,
    hgov_puf_tic                       = ,
    hgov_qhp_ind_dnt                   = ,
    hgov_qhp_ind_med                   = ,
    hgov_qhp_shop_dnt                  = ,
    hgov_qhp_shop_med                  = hgov_temporal(x),
    cli_abort(c("x"                    = "No matches found for {.val {x}}."), call = call)
  )
}

#' Quickly access CMS data
#'
#' Convenience function to quickly access various CMS data endpoints.
#' Mostly for debugging purposes.
#'
#' @param alias  `<chr>` Alias representing the CMS data endpoint or category.
#' @param offset `<int>` The offset for pagination. Default is `0`.
#' @param limit  `<int>` The maximum number of records to retrieve. Default is `10000`.
#' @returns A data frame containing the requested CMS data.
#' @examplesIf rlang::is_interactive()
#' quick("revalid_group")
#' quick("out_img_national")
#' quick("hgov_nipr_state")
#' @autoglobal
#' @export
quick <- function(alias,
                  offset = 0,
                  limit  = 1e4) {

  check_required(alias)

  quick_(
    select_member(alias),
    offset = offset,
    limit  = limit)
}
