#' Quickly access CMS data
#'
#' `quick()` is a convenience function to quickly access various CMS data endpoints.
#' It provides a simple way to retrieve data from different CMS programs and categories.
#'
#' @param x A string representing the CMS data endpoint or category.
#' @param offset An integer representing the offset for pagination. Default is 0.
#' @param limit An integer representing the maximum number of records to retrieve. Default is 10,000.
#' @param call The calling environment. Default is the current environment.
#'
#' @returns A data frame or object containing the requested CMS data.
#'
#' @examples
#' quick("MLR_summary") |> str()
#' @autoglobal
#' @export
quick <- function(x, offset = 0L, limit = 1L, call = caller_env()) {
  ob <- switch(
    x,
    beneficiaries          = ,
    contact                = ,
    crosswalk              = ,
    CARE_dialysis          = ,
    enrollees              = ,
    facilities             = ,
    IQIES                  = ,
    laboratories           = ,
    long_term              = ,
    opt_out                = ,
    order_refer            = ,
    RBCS                   = ,
    transparency           = ,
    prescribers_spending   = ,
    AHRQ_PSI11             = ,
    AIP_spend_plan         = ,
    CPC_primary            = ,
    CPC_joint              = ,
    BENE_risk_spend        = ,
    DRA_HAC_measures       = ,
    ESRD_group             = ,
    MDS_facility           = ,
    MDS_total              = ,
    FISS_rendering         = ,
    HIT_providers          = ,
    CERT                   = ,
    DPP                    = ,
    clinician_group        = ,
    lab_fee_schedule       = ,
    partD_prescribe        = care_endpoint(x),

    HHA                    = ,
    hospice                = ,
    hospital               = ,
    RHC                    = ,
    FQHC                   = ,
    pending                = ,
    reassignment           = ,
    SNF                    = ,
    ACO                    = ,
    program_stats          = ,
    CAID                   = ,
    geo_variation          = ,
    PDP                    = ,
    BENE_surv              = ,
    PTB_drugs              = ,
    MKT                    = care_group(x),

    quality_payment        = ,
    procedure_summary      = ,
    dialysis_facilities    = ,
    aco_shared_savings     = ,
    opioid_treatment       = ,
    hospital_costreport    = care_temporal(x),

    hospital_PSI90 = ,
    hospital_joint = ,
    hospital_footnote = ,
    hospital_update = ,
    hospital_dates = ,
    hospital_maternal = ,
    hospital_outcomes = ,
    hospital_general = ,
    hospital_pi = ,
    hospital_voc_nation = ,
    hospital_voc_hosp = ,
    hospital_pmt_state = ,
    hospital_pmt_nation = ,
    hospital_drg_net = ,
    hospital_drg_dist = ,
    hospital_pmt_pct = ,
    hospital_pmt_vbi = pro_endpoint(x),
    pro_cahps_spice = ,
    pro_cahps_hhc = ,
    pro_cahps_ich = ,
    pro_cahps_oas = ,
    pro_mips = ,
    pro_drs = ,
    pro_ltch = ,
    pro_irf = ,
    pro_hospice = ,
    pro_hhc_vbp = ,
    pro_home_health = ,
    pro_snf_vbp = ,
    pro_snf_quality = ,
    pro_nursing = ,
    pro_complication = ,
    pro_complication_pch = ,
    pro_asc_quality = ,
    pro_equity = ,
    pro_hai = ,
    pro_dialysis = ,
    pro_esrd = ,
    pro_hvbp = ,
    pro_ipf = ,
    pro_mspb = ,
    pro_out_img = ,
    pro_pch_pall = ,
    pro_pch_hcahps = ,
    pro_hcahps = ,
    pro_timely = ,
    pro_unplan = ,
    pro_va = ,
    pro_hospital_changes = ,
    pro_hospital_voc = ,
    pro_reduction = pro_group(x),

    PROF_covered           = ,
    PROF_physician         = ,
    PROF_information       = ,
    PROF_mapping           = ,
    PROF_entity            = ,
    PROF_teaching          = ,
    SUMM_dashboard         = ,
    SUMM_state_all         = ,
    SUMM_state_group       = ,
    SUMM_nation_all        = ,
    SUMM_nation_group      = open_endpoint(x),
    profile                = ,
    summary                = open_group(x),

    ACA_FUL           = ,
    MLR_summary       = ,
    MLTSS_enroll      = ,
    MCD_enterprise    = ,
    DSH_payments      = ,
    DPR_index         = ,
    MDRP_new          = ,
    CAHPS_NAM         = ,
    enroll_mon_test   = ,
    enroll_new_adult  = ,
    pi_data           = ,
    tiles             = caid_endpoint(x),
    demographics      = ,
    services          = ,
    beneficiaries     = ,
    financial         = ,
    NADAC_group       = ,
    PKG               = ,
    DRUG              = ,
    DUAL              = ,
    MEGI              = ,
    CMS64             = ,
    MC                = caid_group(x),

    cli_abort(c("x" = "No matches found for {.val {x}}."), call = call)
  )
  quick_(ob, offset = offset, limit = limit)
}
